// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: .proto/AddMediaToAlbum.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddMediaToAlbum struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	MediaKeys     []string                    `protobuf:"bytes,1,rep,name=media_keys,json=mediaKeys,proto3" json:"media_keys,omitempty"`
	AlbumMediaKey string                      `protobuf:"bytes,2,opt,name=album_media_key,json=albumMediaKey,proto3" json:"album_media_key,omitempty"`
	Field5        *AddMediaToAlbum_Field5Type `protobuf:"bytes,5,opt,name=field5,proto3" json:"field5,omitempty"`
	DeviceInfo    *AddMediaToAlbum_DeviceInfo `protobuf:"bytes,6,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`
	Timestamp     int64                       `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMediaToAlbum) Reset() {
	*x = AddMediaToAlbum{}
	mi := &file___proto_AddMediaToAlbum_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMediaToAlbum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMediaToAlbum) ProtoMessage() {}

func (x *AddMediaToAlbum) ProtoReflect() protoreflect.Message {
	mi := &file___proto_AddMediaToAlbum_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMediaToAlbum.ProtoReflect.Descriptor instead.
func (*AddMediaToAlbum) Descriptor() ([]byte, []int) {
	return file___proto_AddMediaToAlbum_proto_rawDescGZIP(), []int{0}
}

func (x *AddMediaToAlbum) GetMediaKeys() []string {
	if x != nil {
		return x.MediaKeys
	}
	return nil
}

func (x *AddMediaToAlbum) GetAlbumMediaKey() string {
	if x != nil {
		return x.AlbumMediaKey
	}
	return ""
}

func (x *AddMediaToAlbum) GetField5() *AddMediaToAlbum_Field5Type {
	if x != nil {
		return x.Field5
	}
	return nil
}

func (x *AddMediaToAlbum) GetDeviceInfo() *AddMediaToAlbum_DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

func (x *AddMediaToAlbum) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type AddMediaToAlbum_Field5Type struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field1        int64                  `protobuf:"varint,1,opt,name=field1,proto3" json:"field1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMediaToAlbum_Field5Type) Reset() {
	*x = AddMediaToAlbum_Field5Type{}
	mi := &file___proto_AddMediaToAlbum_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMediaToAlbum_Field5Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMediaToAlbum_Field5Type) ProtoMessage() {}

func (x *AddMediaToAlbum_Field5Type) ProtoReflect() protoreflect.Message {
	mi := &file___proto_AddMediaToAlbum_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMediaToAlbum_Field5Type.ProtoReflect.Descriptor instead.
func (*AddMediaToAlbum_Field5Type) Descriptor() ([]byte, []int) {
	return file___proto_AddMediaToAlbum_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AddMediaToAlbum_Field5Type) GetField1() int64 {
	if x != nil {
		return x.Field1
	}
	return 0
}

type AddMediaToAlbum_DeviceInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Model             string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Make              string                 `protobuf:"bytes,4,opt,name=make,proto3" json:"make,omitempty"`
	AndroidApiVersion int64                  `protobuf:"varint,5,opt,name=android_api_version,json=androidApiVersion,proto3" json:"android_api_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AddMediaToAlbum_DeviceInfo) Reset() {
	*x = AddMediaToAlbum_DeviceInfo{}
	mi := &file___proto_AddMediaToAlbum_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMediaToAlbum_DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMediaToAlbum_DeviceInfo) ProtoMessage() {}

func (x *AddMediaToAlbum_DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file___proto_AddMediaToAlbum_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMediaToAlbum_DeviceInfo.ProtoReflect.Descriptor instead.
func (*AddMediaToAlbum_DeviceInfo) Descriptor() ([]byte, []int) {
	return file___proto_AddMediaToAlbum_proto_rawDescGZIP(), []int{0, 1}
}

func (x *AddMediaToAlbum_DeviceInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AddMediaToAlbum_DeviceInfo) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *AddMediaToAlbum_DeviceInfo) GetAndroidApiVersion() int64 {
	if x != nil {
		return x.AndroidApiVersion
	}
	return 0
}

var File___proto_AddMediaToAlbum_proto protoreflect.FileDescriptor

const file___proto_AddMediaToAlbum_proto_rawDesc = "" +
	"\n" +
	"\x1c.proto/AddMediaToAlbum.proto\"\xf7\x02\n" +
	"\x0fAddMediaToAlbum\x12\x1d\n" +
	"\n" +
	"media_keys\x18\x01 \x03(\tR\tmediaKeys\x12&\n" +
	"\x0falbum_media_key\x18\x02 \x01(\tR\ralbumMediaKey\x123\n" +
	"\x06field5\x18\x05 \x01(\v2\x1b.AddMediaToAlbum.Field5TypeR\x06field5\x12<\n" +
	"\vdevice_info\x18\x06 \x01(\v2\x1b.AddMediaToAlbum.DeviceInfoR\n" +
	"deviceInfo\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x1a$\n" +
	"\n" +
	"Field5Type\x12\x16\n" +
	"\x06field1\x18\x01 \x01(\x03R\x06field1\x1af\n" +
	"\n" +
	"DeviceInfo\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04make\x18\x04 \x01(\tR\x04make\x12.\n" +
	"\x13android_api_version\x18\x05 \x01(\x03R\x11androidApiVersionB\x05Z\x03/pbb\x06proto3"

var (
	file___proto_AddMediaToAlbum_proto_rawDescOnce sync.Once
	file___proto_AddMediaToAlbum_proto_rawDescData []byte
)

func file___proto_AddMediaToAlbum_proto_rawDescGZIP() []byte {
	file___proto_AddMediaToAlbum_proto_rawDescOnce.Do(func() {
		file___proto_AddMediaToAlbum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file___proto_AddMediaToAlbum_proto_rawDesc), len(file___proto_AddMediaToAlbum_proto_rawDesc)))
	})
	return file___proto_AddMediaToAlbum_proto_rawDescData
}

var file___proto_AddMediaToAlbum_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file___proto_AddMediaToAlbum_proto_goTypes = []any{
	(*AddMediaToAlbum)(nil),            // 0: AddMediaToAlbum
	(*AddMediaToAlbum_Field5Type)(nil), // 1: AddMediaToAlbum.Field5Type
	(*AddMediaToAlbum_DeviceInfo)(nil), // 2: AddMediaToAlbum.DeviceInfo
}
var file___proto_AddMediaToAlbum_proto_depIdxs = []int32{
	1, // 0: AddMediaToAlbum.field5:type_name -> AddMediaToAlbum.Field5Type
	2, // 1: AddMediaToAlbum.device_info:type_name -> AddMediaToAlbum.DeviceInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file___proto_AddMediaToAlbum_proto_init() }
func file___proto_AddMediaToAlbum_proto_init() {
	if File___proto_AddMediaToAlbum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file___proto_AddMediaToAlbum_proto_rawDesc), len(file___proto_AddMediaToAlbum_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file___proto_AddMediaToAlbum_proto_goTypes,
		DependencyIndexes: file___proto_AddMediaToAlbum_proto_depIdxs,
		MessageInfos:      file___proto_AddMediaToAlbum_proto_msgTypes,
	}.Build()
	File___proto_AddMediaToAlbum_proto = out.File
	file___proto_AddMediaToAlbum_proto_goTypes = nil
	file___proto_AddMediaToAlbum_proto_depIdxs = nil
}
