// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: .proto/ArchiveAction.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArchiveActionType int32

const (
	ArchiveActionType_ARCHIVE_ACTION_UNSPECIFIED ArchiveActionType = 0 // Required for proto3, not used
	ArchiveActionType_ARCHIVE                    ArchiveActionType = 1
	ArchiveActionType_UNARCHIVE                  ArchiveActionType = 2
)

// Enum value maps for ArchiveActionType.
var (
	ArchiveActionType_name = map[int32]string{
		0: "ARCHIVE_ACTION_UNSPECIFIED",
		1: "ARCHIVE",
		2: "UNARCHIVE",
	}
	ArchiveActionType_value = map[string]int32{
		"ARCHIVE_ACTION_UNSPECIFIED": 0,
		"ARCHIVE":                    1,
		"UNARCHIVE":                  2,
	}
)

func (x ArchiveActionType) Enum() *ArchiveActionType {
	p := new(ArchiveActionType)
	*p = x
	return p
}

func (x ArchiveActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArchiveActionType) Descriptor() protoreflect.EnumDescriptor {
	return file___proto_ArchiveAction_proto_enumTypes[0].Descriptor()
}

func (ArchiveActionType) Type() protoreflect.EnumType {
	return &file___proto_ArchiveAction_proto_enumTypes[0]
}

func (x ArchiveActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArchiveActionType.Descriptor instead.
func (ArchiveActionType) EnumDescriptor() ([]byte, []int) {
	return file___proto_ArchiveAction_proto_rawDescGZIP(), []int{0}
}

// ArchiveItems is used to archive or unarchive media items
type ArchiveItems struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ArchiveItems_Item   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Field3        int64                  `protobuf:"varint,3,opt,name=field3,proto3" json:"field3,omitempty"` // constant: 1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveItems) Reset() {
	*x = ArchiveItems{}
	mi := &file___proto_ArchiveAction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveItems) ProtoMessage() {}

func (x *ArchiveItems) ProtoReflect() protoreflect.Message {
	mi := &file___proto_ArchiveAction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveItems.ProtoReflect.Descriptor instead.
func (*ArchiveItems) Descriptor() ([]byte, []int) {
	return file___proto_ArchiveAction_proto_rawDescGZIP(), []int{0}
}

func (x *ArchiveItems) GetItems() []*ArchiveItems_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ArchiveItems) GetField3() int64 {
	if x != nil {
		return x.Field3
	}
	return 0
}

type ArchiveItems_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemKey       string                 `protobuf:"bytes,1,opt,name=item_key,json=itemKey,proto3" json:"item_key,omitempty"` // mediaKey or dedupKey (URL-safe base64 encoded SHA1 hash)
	Action        *ArchiveItems_Action   `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveItems_Item) Reset() {
	*x = ArchiveItems_Item{}
	mi := &file___proto_ArchiveAction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveItems_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveItems_Item) ProtoMessage() {}

func (x *ArchiveItems_Item) ProtoReflect() protoreflect.Message {
	mi := &file___proto_ArchiveAction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveItems_Item.ProtoReflect.Descriptor instead.
func (*ArchiveItems_Item) Descriptor() ([]byte, []int) {
	return file___proto_ArchiveAction_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ArchiveItems_Item) GetItemKey() string {
	if x != nil {
		return x.ItemKey
	}
	return ""
}

func (x *ArchiveItems_Item) GetAction() *ArchiveItems_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

type ArchiveItems_Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        ArchiveActionType      `protobuf:"varint,1,opt,name=action,proto3,enum=ArchiveActionType" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveItems_Action) Reset() {
	*x = ArchiveItems_Action{}
	mi := &file___proto_ArchiveAction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveItems_Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveItems_Action) ProtoMessage() {}

func (x *ArchiveItems_Action) ProtoReflect() protoreflect.Message {
	mi := &file___proto_ArchiveAction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveItems_Action.ProtoReflect.Descriptor instead.
func (*ArchiveItems_Action) Descriptor() ([]byte, []int) {
	return file___proto_ArchiveAction_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ArchiveItems_Action) GetAction() ArchiveActionType {
	if x != nil {
		return x.Action
	}
	return ArchiveActionType_ARCHIVE_ACTION_UNSPECIFIED
}

var File___proto_ArchiveAction_proto protoreflect.FileDescriptor

const file___proto_ArchiveAction_proto_rawDesc = "" +
	"\n" +
	"\x1a.proto/ArchiveAction.proto\"\xd7\x01\n" +
	"\fArchiveItems\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.ArchiveItems.ItemR\x05items\x12\x16\n" +
	"\x06field3\x18\x03 \x01(\x03R\x06field3\x1aO\n" +
	"\x04Item\x12\x19\n" +
	"\bitem_key\x18\x01 \x01(\tR\aitemKey\x12,\n" +
	"\x06action\x18\x02 \x01(\v2\x14.ArchiveItems.ActionR\x06action\x1a4\n" +
	"\x06Action\x12*\n" +
	"\x06action\x18\x01 \x01(\x0e2\x12.ArchiveActionTypeR\x06action*O\n" +
	"\x11ArchiveActionType\x12\x1e\n" +
	"\x1aARCHIVE_ACTION_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aARCHIVE\x10\x01\x12\r\n" +
	"\tUNARCHIVE\x10\x02B.Z,github.com/viperadnan-git/go-gpm/internal/pbb\x06proto3"

var (
	file___proto_ArchiveAction_proto_rawDescOnce sync.Once
	file___proto_ArchiveAction_proto_rawDescData []byte
)

func file___proto_ArchiveAction_proto_rawDescGZIP() []byte {
	file___proto_ArchiveAction_proto_rawDescOnce.Do(func() {
		file___proto_ArchiveAction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file___proto_ArchiveAction_proto_rawDesc), len(file___proto_ArchiveAction_proto_rawDesc)))
	})
	return file___proto_ArchiveAction_proto_rawDescData
}

var file___proto_ArchiveAction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file___proto_ArchiveAction_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file___proto_ArchiveAction_proto_goTypes = []any{
	(ArchiveActionType)(0),      // 0: ArchiveActionType
	(*ArchiveItems)(nil),        // 1: ArchiveItems
	(*ArchiveItems_Item)(nil),   // 2: ArchiveItems.Item
	(*ArchiveItems_Action)(nil), // 3: ArchiveItems.Action
}
var file___proto_ArchiveAction_proto_depIdxs = []int32{
	2, // 0: ArchiveItems.items:type_name -> ArchiveItems.Item
	3, // 1: ArchiveItems.Item.action:type_name -> ArchiveItems.Action
	0, // 2: ArchiveItems.Action.action:type_name -> ArchiveActionType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file___proto_ArchiveAction_proto_init() }
func file___proto_ArchiveAction_proto_init() {
	if File___proto_ArchiveAction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file___proto_ArchiveAction_proto_rawDesc), len(file___proto_ArchiveAction_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file___proto_ArchiveAction_proto_goTypes,
		DependencyIndexes: file___proto_ArchiveAction_proto_depIdxs,
		EnumInfos:         file___proto_ArchiveAction_proto_enumTypes,
		MessageInfos:      file___proto_ArchiveAction_proto_msgTypes,
	}.Build()
	File___proto_ArchiveAction_proto = out.File
	file___proto_ArchiveAction_proto_goTypes = nil
	file___proto_ArchiveAction_proto_depIdxs = nil
}
