// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: .proto/CreateAlbum.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAlbum struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	AlbumName     string                     `protobuf:"bytes,1,opt,name=album_name,json=albumName,proto3" json:"album_name,omitempty"`
	Timestamp     int64                      `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Field3        int64                      `protobuf:"varint,3,opt,name=field3,proto3" json:"field3,omitempty"`
	MediaKeys     []*CreateAlbum_MediaKeyRef `protobuf:"bytes,4,rep,name=media_keys,json=mediaKeys,proto3" json:"media_keys,omitempty"`
	Field6        *CreateAlbum_Field6Type    `protobuf:"bytes,6,opt,name=field6,proto3" json:"field6,omitempty"`
	Field7        *CreateAlbum_Field7Type    `protobuf:"bytes,7,opt,name=field7,proto3" json:"field7,omitempty"`
	DeviceInfo    *CreateAlbum_DeviceInfo    `protobuf:"bytes,8,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlbum) Reset() {
	*x = CreateAlbum{}
	mi := &file___proto_CreateAlbum_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlbum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlbum) ProtoMessage() {}

func (x *CreateAlbum) ProtoReflect() protoreflect.Message {
	mi := &file___proto_CreateAlbum_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlbum.ProtoReflect.Descriptor instead.
func (*CreateAlbum) Descriptor() ([]byte, []int) {
	return file___proto_CreateAlbum_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAlbum) GetAlbumName() string {
	if x != nil {
		return x.AlbumName
	}
	return ""
}

func (x *CreateAlbum) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CreateAlbum) GetField3() int64 {
	if x != nil {
		return x.Field3
	}
	return 0
}

func (x *CreateAlbum) GetMediaKeys() []*CreateAlbum_MediaKeyRef {
	if x != nil {
		return x.MediaKeys
	}
	return nil
}

func (x *CreateAlbum) GetField6() *CreateAlbum_Field6Type {
	if x != nil {
		return x.Field6
	}
	return nil
}

func (x *CreateAlbum) GetField7() *CreateAlbum_Field7Type {
	if x != nil {
		return x.Field7
	}
	return nil
}

func (x *CreateAlbum) GetDeviceInfo() *CreateAlbum_DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

type CreateAlbumResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Field1        *CreateAlbumResponse_Field1Type `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlbumResponse) Reset() {
	*x = CreateAlbumResponse{}
	mi := &file___proto_CreateAlbum_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlbumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlbumResponse) ProtoMessage() {}

func (x *CreateAlbumResponse) ProtoReflect() protoreflect.Message {
	mi := &file___proto_CreateAlbum_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlbumResponse.ProtoReflect.Descriptor instead.
func (*CreateAlbumResponse) Descriptor() ([]byte, []int) {
	return file___proto_CreateAlbum_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAlbumResponse) GetField1() *CreateAlbumResponse_Field1Type {
	if x != nil {
		return x.Field1
	}
	return nil
}

type CreateAlbum_MediaKeyRef struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Field1        *CreateAlbum_MediaKeyRef_MediaKeyInner `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlbum_MediaKeyRef) Reset() {
	*x = CreateAlbum_MediaKeyRef{}
	mi := &file___proto_CreateAlbum_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlbum_MediaKeyRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlbum_MediaKeyRef) ProtoMessage() {}

func (x *CreateAlbum_MediaKeyRef) ProtoReflect() protoreflect.Message {
	mi := &file___proto_CreateAlbum_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlbum_MediaKeyRef.ProtoReflect.Descriptor instead.
func (*CreateAlbum_MediaKeyRef) Descriptor() ([]byte, []int) {
	return file___proto_CreateAlbum_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CreateAlbum_MediaKeyRef) GetField1() *CreateAlbum_MediaKeyRef_MediaKeyInner {
	if x != nil {
		return x.Field1
	}
	return nil
}

type CreateAlbum_Field6Type struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlbum_Field6Type) Reset() {
	*x = CreateAlbum_Field6Type{}
	mi := &file___proto_CreateAlbum_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlbum_Field6Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlbum_Field6Type) ProtoMessage() {}

func (x *CreateAlbum_Field6Type) ProtoReflect() protoreflect.Message {
	mi := &file___proto_CreateAlbum_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlbum_Field6Type.ProtoReflect.Descriptor instead.
func (*CreateAlbum_Field6Type) Descriptor() ([]byte, []int) {
	return file___proto_CreateAlbum_proto_rawDescGZIP(), []int{0, 1}
}

type CreateAlbum_Field7Type struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field1        int64                  `protobuf:"varint,1,opt,name=field1,proto3" json:"field1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlbum_Field7Type) Reset() {
	*x = CreateAlbum_Field7Type{}
	mi := &file___proto_CreateAlbum_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlbum_Field7Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlbum_Field7Type) ProtoMessage() {}

func (x *CreateAlbum_Field7Type) ProtoReflect() protoreflect.Message {
	mi := &file___proto_CreateAlbum_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlbum_Field7Type.ProtoReflect.Descriptor instead.
func (*CreateAlbum_Field7Type) Descriptor() ([]byte, []int) {
	return file___proto_CreateAlbum_proto_rawDescGZIP(), []int{0, 2}
}

func (x *CreateAlbum_Field7Type) GetField1() int64 {
	if x != nil {
		return x.Field1
	}
	return 0
}

type CreateAlbum_DeviceInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Model             string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Make              string                 `protobuf:"bytes,4,opt,name=make,proto3" json:"make,omitempty"`
	AndroidApiVersion int64                  `protobuf:"varint,5,opt,name=android_api_version,json=androidApiVersion,proto3" json:"android_api_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateAlbum_DeviceInfo) Reset() {
	*x = CreateAlbum_DeviceInfo{}
	mi := &file___proto_CreateAlbum_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlbum_DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlbum_DeviceInfo) ProtoMessage() {}

func (x *CreateAlbum_DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file___proto_CreateAlbum_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlbum_DeviceInfo.ProtoReflect.Descriptor instead.
func (*CreateAlbum_DeviceInfo) Descriptor() ([]byte, []int) {
	return file___proto_CreateAlbum_proto_rawDescGZIP(), []int{0, 3}
}

func (x *CreateAlbum_DeviceInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateAlbum_DeviceInfo) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *CreateAlbum_DeviceInfo) GetAndroidApiVersion() int64 {
	if x != nil {
		return x.AndroidApiVersion
	}
	return 0
}

type CreateAlbum_MediaKeyRef_MediaKeyInner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaKey      string                 `protobuf:"bytes,1,opt,name=media_key,json=mediaKey,proto3" json:"media_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlbum_MediaKeyRef_MediaKeyInner) Reset() {
	*x = CreateAlbum_MediaKeyRef_MediaKeyInner{}
	mi := &file___proto_CreateAlbum_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlbum_MediaKeyRef_MediaKeyInner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlbum_MediaKeyRef_MediaKeyInner) ProtoMessage() {}

func (x *CreateAlbum_MediaKeyRef_MediaKeyInner) ProtoReflect() protoreflect.Message {
	mi := &file___proto_CreateAlbum_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlbum_MediaKeyRef_MediaKeyInner.ProtoReflect.Descriptor instead.
func (*CreateAlbum_MediaKeyRef_MediaKeyInner) Descriptor() ([]byte, []int) {
	return file___proto_CreateAlbum_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *CreateAlbum_MediaKeyRef_MediaKeyInner) GetMediaKey() string {
	if x != nil {
		return x.MediaKey
	}
	return ""
}

type CreateAlbumResponse_Field1Type struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlbumMediaKey string                 `protobuf:"bytes,1,opt,name=album_media_key,json=albumMediaKey,proto3" json:"album_media_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlbumResponse_Field1Type) Reset() {
	*x = CreateAlbumResponse_Field1Type{}
	mi := &file___proto_CreateAlbum_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlbumResponse_Field1Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlbumResponse_Field1Type) ProtoMessage() {}

func (x *CreateAlbumResponse_Field1Type) ProtoReflect() protoreflect.Message {
	mi := &file___proto_CreateAlbum_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlbumResponse_Field1Type.ProtoReflect.Descriptor instead.
func (*CreateAlbumResponse_Field1Type) Descriptor() ([]byte, []int) {
	return file___proto_CreateAlbum_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CreateAlbumResponse_Field1Type) GetAlbumMediaKey() string {
	if x != nil {
		return x.AlbumMediaKey
	}
	return ""
}

var File___proto_CreateAlbum_proto protoreflect.FileDescriptor

const file___proto_CreateAlbum_proto_rawDesc = "" +
	"\n" +
	"\x18.proto/CreateAlbum.proto\"\xd0\x04\n" +
	"\vCreateAlbum\x12\x1d\n" +
	"\n" +
	"album_name\x18\x01 \x01(\tR\talbumName\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06field3\x18\x03 \x01(\x03R\x06field3\x127\n" +
	"\n" +
	"media_keys\x18\x04 \x03(\v2\x18.CreateAlbum.MediaKeyRefR\tmediaKeys\x12/\n" +
	"\x06field6\x18\x06 \x01(\v2\x17.CreateAlbum.Field6TypeR\x06field6\x12/\n" +
	"\x06field7\x18\a \x01(\v2\x17.CreateAlbum.Field7TypeR\x06field7\x128\n" +
	"\vdevice_info\x18\b \x01(\v2\x17.CreateAlbum.DeviceInfoR\n" +
	"deviceInfo\x1a{\n" +
	"\vMediaKeyRef\x12>\n" +
	"\x06field1\x18\x01 \x01(\v2&.CreateAlbum.MediaKeyRef.MediaKeyInnerR\x06field1\x1a,\n" +
	"\rMediaKeyInner\x12\x1b\n" +
	"\tmedia_key\x18\x01 \x01(\tR\bmediaKey\x1a\f\n" +
	"\n" +
	"Field6Type\x1a$\n" +
	"\n" +
	"Field7Type\x12\x16\n" +
	"\x06field1\x18\x01 \x01(\x03R\x06field1\x1af\n" +
	"\n" +
	"DeviceInfo\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04make\x18\x04 \x01(\tR\x04make\x12.\n" +
	"\x13android_api_version\x18\x05 \x01(\x03R\x11androidApiVersion\"\x84\x01\n" +
	"\x13CreateAlbumResponse\x127\n" +
	"\x06field1\x18\x01 \x01(\v2\x1f.CreateAlbumResponse.Field1TypeR\x06field1\x1a4\n" +
	"\n" +
	"Field1Type\x12&\n" +
	"\x0falbum_media_key\x18\x01 \x01(\tR\ralbumMediaKeyB\x05Z\x03/pbb\x06proto3"

var (
	file___proto_CreateAlbum_proto_rawDescOnce sync.Once
	file___proto_CreateAlbum_proto_rawDescData []byte
)

func file___proto_CreateAlbum_proto_rawDescGZIP() []byte {
	file___proto_CreateAlbum_proto_rawDescOnce.Do(func() {
		file___proto_CreateAlbum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file___proto_CreateAlbum_proto_rawDesc), len(file___proto_CreateAlbum_proto_rawDesc)))
	})
	return file___proto_CreateAlbum_proto_rawDescData
}

var file___proto_CreateAlbum_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file___proto_CreateAlbum_proto_goTypes = []any{
	(*CreateAlbum)(nil),                           // 0: CreateAlbum
	(*CreateAlbumResponse)(nil),                   // 1: CreateAlbumResponse
	(*CreateAlbum_MediaKeyRef)(nil),               // 2: CreateAlbum.MediaKeyRef
	(*CreateAlbum_Field6Type)(nil),                // 3: CreateAlbum.Field6Type
	(*CreateAlbum_Field7Type)(nil),                // 4: CreateAlbum.Field7Type
	(*CreateAlbum_DeviceInfo)(nil),                // 5: CreateAlbum.DeviceInfo
	(*CreateAlbum_MediaKeyRef_MediaKeyInner)(nil), // 6: CreateAlbum.MediaKeyRef.MediaKeyInner
	(*CreateAlbumResponse_Field1Type)(nil),        // 7: CreateAlbumResponse.Field1Type
}
var file___proto_CreateAlbum_proto_depIdxs = []int32{
	2, // 0: CreateAlbum.media_keys:type_name -> CreateAlbum.MediaKeyRef
	3, // 1: CreateAlbum.field6:type_name -> CreateAlbum.Field6Type
	4, // 2: CreateAlbum.field7:type_name -> CreateAlbum.Field7Type
	5, // 3: CreateAlbum.device_info:type_name -> CreateAlbum.DeviceInfo
	7, // 4: CreateAlbumResponse.field1:type_name -> CreateAlbumResponse.Field1Type
	6, // 5: CreateAlbum.MediaKeyRef.field1:type_name -> CreateAlbum.MediaKeyRef.MediaKeyInner
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file___proto_CreateAlbum_proto_init() }
func file___proto_CreateAlbum_proto_init() {
	if File___proto_CreateAlbum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file___proto_CreateAlbum_proto_rawDesc), len(file___proto_CreateAlbum_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file___proto_CreateAlbum_proto_goTypes,
		DependencyIndexes: file___proto_CreateAlbum_proto_depIdxs,
		MessageInfos:      file___proto_CreateAlbum_proto_msgTypes,
	}.Build()
	File___proto_CreateAlbum_proto = out.File
	file___proto_CreateAlbum_proto_goTypes = nil
	file___proto_CreateAlbum_proto_depIdxs = nil
}
