// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: .proto/LibraryState.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LibraryStateResponse is the response from library state APIs
type LibraryStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *LibraryStateData      `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // Main response data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LibraryStateResponse) Reset() {
	*x = LibraryStateResponse{}
	mi := &file___proto_LibraryState_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LibraryStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibraryStateResponse) ProtoMessage() {}

func (x *LibraryStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file___proto_LibraryState_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LibraryStateResponse.ProtoReflect.Descriptor instead.
func (*LibraryStateResponse) Descriptor() ([]byte, []int) {
	return file___proto_LibraryState_proto_rawDescGZIP(), []int{0}
}

func (x *LibraryStateResponse) GetData() *LibraryStateData {
	if x != nil {
		return x.Data
	}
	return nil
}

// LibraryStateData contains the main library state information
type LibraryStateData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextPageToken string                 `protobuf:"bytes,1,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"` // Pagination token for next page
	MediaItems    []*MediaItemData       `protobuf:"bytes,2,rep,name=media_items,json=mediaItems,proto3" json:"media_items,omitempty"`            // Media items in library
	Albums        []*AlbumData           `protobuf:"bytes,3,rep,name=albums,proto3" json:"albums,omitempty"`                                      // Albums/collections
	StateToken    string                 `protobuf:"bytes,6,opt,name=state_token,json=stateToken,proto3" json:"state_token,omitempty"`            // State token for incremental sync
	Deletions     []*DeletionData        `protobuf:"bytes,9,rep,name=deletions,proto3" json:"deletions,omitempty"`                                // Deleted items
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LibraryStateData) Reset() {
	*x = LibraryStateData{}
	mi := &file___proto_LibraryState_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LibraryStateData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibraryStateData) ProtoMessage() {}

func (x *LibraryStateData) ProtoReflect() protoreflect.Message {
	mi := &file___proto_LibraryState_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LibraryStateData.ProtoReflect.Descriptor instead.
func (*LibraryStateData) Descriptor() ([]byte, []int) {
	return file___proto_LibraryState_proto_rawDescGZIP(), []int{1}
}

func (x *LibraryStateData) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *LibraryStateData) GetMediaItems() []*MediaItemData {
	if x != nil {
		return x.MediaItems
	}
	return nil
}

func (x *LibraryStateData) GetAlbums() []*AlbumData {
	if x != nil {
		return x.Albums
	}
	return nil
}

func (x *LibraryStateData) GetStateToken() string {
	if x != nil {
		return x.StateToken
	}
	return ""
}

func (x *LibraryStateData) GetDeletions() []*DeletionData {
	if x != nil {
		return x.Deletions
	}
	return nil
}

// MediaItemData represents a media item (photo/video)
type MediaItemData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaKey      string                 `protobuf:"bytes,1,opt,name=media_key,json=mediaKey,proto3" json:"media_key,omitempty"` // Unique identifier for the media item
	Metadata      *MediaMetadata         `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`                 // Media metadata
	TypeInfo      *MediaTypeInfo         `protobuf:"bytes,5,opt,name=type_info,json=typeInfo,proto3" json:"type_info,omitempty"` // Type and format information
	KeyInfo       *MediaKeyInfo          `protobuf:"bytes,6,opt,name=key_info,json=keyInfo,proto3" json:"key_info,omitempty"`    // Alternative key information
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaItemData) Reset() {
	*x = MediaItemData{}
	mi := &file___proto_LibraryState_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaItemData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaItemData) ProtoMessage() {}

func (x *MediaItemData) ProtoReflect() protoreflect.Message {
	mi := &file___proto_LibraryState_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaItemData.ProtoReflect.Descriptor instead.
func (*MediaItemData) Descriptor() ([]byte, []int) {
	return file___proto_LibraryState_proto_rawDescGZIP(), []int{2}
}

func (x *MediaItemData) GetMediaKey() string {
	if x != nil {
		return x.MediaKey
	}
	return ""
}

func (x *MediaItemData) GetMetadata() *MediaMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MediaItemData) GetTypeInfo() *MediaTypeInfo {
	if x != nil {
		return x.TypeInfo
	}
	return nil
}

func (x *MediaItemData) GetKeyInfo() *MediaKeyInfo {
	if x != nil {
		return x.KeyInfo
	}
	return nil
}

// MediaMetadata contains metadata for a media item
type MediaMetadata struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Collection *CollectionInfo        `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"` // Collection/album association
	// Field 3: Caption (string, position varies)
	FileName   string          `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"` // Original filename
	Properties []*PropertyInfo `protobuf:"bytes,5,rep,name=properties,proto3" json:"properties,omitempty"`             // Properties list (property 27 = non-canonical)
	// Field 6: Unknown
	UtcTimestamp            uint64 `protobuf:"varint,7,opt,name=utc_timestamp,json=utcTimestamp,proto3" json:"utc_timestamp,omitempty"`                                    // Capture timestamp in milliseconds
	TimezoneOffset          uint64 `protobuf:"varint,8,opt,name=timezone_offset,json=timezoneOffset,proto3" json:"timezone_offset,omitempty"`                              // Timezone offset in milliseconds
	ServerCreationTimestamp uint64 `protobuf:"varint,9,opt,name=server_creation_timestamp,json=serverCreationTimestamp,proto3" json:"server_creation_timestamp,omitempty"` // Server upload timestamp
	SizeBytes               uint64 `protobuf:"varint,10,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`                                            // File size in bytes
	UploadStatus            uint64 `protobuf:"varint,11,opt,name=upload_status,json=uploadStatus,proto3" json:"upload_status,omitempty"`                                   // Upload status
	// Field 13: Hash data
	// Field 16: Trash info (field 16.3 = trash_timestamp)
	Dedup          *DedupInfo   `protobuf:"bytes,21,opt,name=dedup,proto3" json:"dedup,omitempty"`                                          // Deduplication key info
	ContentVersion uint64       `protobuf:"varint,26,opt,name=content_version,json=contentVersion,proto3" json:"content_version,omitempty"` // Content version number
	Archive        *ArchiveInfo `protobuf:"bytes,29,opt,name=archive,proto3" json:"archive,omitempty"`                                      // Archive status
	// Field 30: Origin info (1=self, 3=partner, 4=shared)
	Favorite      *FavoriteInfo `protobuf:"bytes,31,opt,name=favorite,proto3" json:"favorite,omitempty"` // Favorite status
	Quota         *QuotaInfo    `protobuf:"bytes,35,opt,name=quota,proto3" json:"quota,omitempty"`       // Storage quota info
	Lock          *LockInfo     `protobuf:"bytes,39,opt,name=lock,proto3" json:"lock,omitempty"`         // Lock status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaMetadata) Reset() {
	*x = MediaMetadata{}
	mi := &file___proto_LibraryState_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaMetadata) ProtoMessage() {}

func (x *MediaMetadata) ProtoReflect() protoreflect.Message {
	mi := &file___proto_LibraryState_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaMetadata.ProtoReflect.Descriptor instead.
func (*MediaMetadata) Descriptor() ([]byte, []int) {
	return file___proto_LibraryState_proto_rawDescGZIP(), []int{3}
}

func (x *MediaMetadata) GetCollection() *CollectionInfo {
	if x != nil {
		return x.Collection
	}
	return nil
}

func (x *MediaMetadata) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *MediaMetadata) GetProperties() []*PropertyInfo {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *MediaMetadata) GetUtcTimestamp() uint64 {
	if x != nil {
		return x.UtcTimestamp
	}
	return 0
}

func (x *MediaMetadata) GetTimezoneOffset() uint64 {
	if x != nil {
		return x.TimezoneOffset
	}
	return 0
}

func (x *MediaMetadata) GetServerCreationTimestamp() uint64 {
	if x != nil {
		return x.ServerCreationTimestamp
	}
	return 0
}

func (x *MediaMetadata) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *MediaMetadata) GetUploadStatus() uint64 {
	if x != nil {
		return x.UploadStatus
	}
	return 0
}

func (x *MediaMetadata) GetDedup() *DedupInfo {
	if x != nil {
		return x.Dedup
	}
	return nil
}

func (x *MediaMetadata) GetContentVersion() uint64 {
	if x != nil {
		return x.ContentVersion
	}
	return 0
}

func (x *MediaMetadata) GetArchive() *ArchiveInfo {
	if x != nil {
		return x.Archive
	}
	return nil
}

func (x *MediaMetadata) GetFavorite() *FavoriteInfo {
	if x != nil {
		return x.Favorite
	}
	return nil
}

func (x *MediaMetadata) GetQuota() *QuotaInfo {
	if x != nil {
		return x.Quota
	}
	return nil
}

func (x *MediaMetadata) GetLock() *LockInfo {
	if x != nil {
		return x.Lock
	}
	return nil
}

// CollectionInfo links media to a collection/album
type CollectionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectionId  string                 `protobuf:"bytes,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"` // Collection/album identifier
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionInfo) Reset() {
	*x = CollectionInfo{}
	mi := &file___proto_LibraryState_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionInfo) ProtoMessage() {}

func (x *CollectionInfo) ProtoReflect() protoreflect.Message {
	mi := &file___proto_LibraryState_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionInfo.ProtoReflect.Descriptor instead.
func (*CollectionInfo) Descriptor() ([]byte, []int) {
	return file___proto_LibraryState_proto_rawDescGZIP(), []int{4}
}

func (x *CollectionInfo) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

// PropertyInfo represents a property marker
type PropertyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PropertyId    uint64                 `protobuf:"varint,1,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"` // Property ID (27 = non-canonical marker)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertyInfo) Reset() {
	*x = PropertyInfo{}
	mi := &file___proto_LibraryState_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyInfo) ProtoMessage() {}

func (x *PropertyInfo) ProtoReflect() protoreflect.Message {
	mi := &file___proto_LibraryState_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyInfo.ProtoReflect.Descriptor instead.
func (*PropertyInfo) Descriptor() ([]byte, []int) {
	return file___proto_LibraryState_proto_rawDescGZIP(), []int{5}
}

func (x *PropertyInfo) GetPropertyId() uint64 {
	if x != nil {
		return x.PropertyId
	}
	return 0
}

// DedupInfo contains deduplication information
type DedupInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DedupKey      string                 `protobuf:"bytes,1,opt,name=dedup_key,json=dedupKey,proto3" json:"dedup_key,omitempty"` // Deduplication key (same for duplicates)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DedupInfo) Reset() {
	*x = DedupInfo{}
	mi := &file___proto_LibraryState_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DedupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DedupInfo) ProtoMessage() {}

func (x *DedupInfo) ProtoReflect() protoreflect.Message {
	mi := &file___proto_LibraryState_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DedupInfo.ProtoReflect.Descriptor instead.
func (*DedupInfo) Descriptor() ([]byte, []int) {
	return file___proto_LibraryState_proto_rawDescGZIP(), []int{6}
}

func (x *DedupInfo) GetDedupKey() string {
	if x != nil {
		return x.DedupKey
	}
	return ""
}

// ArchiveInfo contains archive status
type ArchiveInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        uint64                 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` // 1=archived, 2=not archived
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveInfo) Reset() {
	*x = ArchiveInfo{}
	mi := &file___proto_LibraryState_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveInfo) ProtoMessage() {}

func (x *ArchiveInfo) ProtoReflect() protoreflect.Message {
	mi := &file___proto_LibraryState_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveInfo.ProtoReflect.Descriptor instead.
func (*ArchiveInfo) Descriptor() ([]byte, []int) {
	return file___proto_LibraryState_proto_rawDescGZIP(), []int{7}
}

func (x *ArchiveInfo) GetStatus() uint64 {
	if x != nil {
		return x.Status
	}
	return 0
}

// FavoriteInfo contains favorite status
type FavoriteInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        uint64                 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` // 1=favorite, 2=not favorite
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteInfo) Reset() {
	*x = FavoriteInfo{}
	mi := &file___proto_LibraryState_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteInfo) ProtoMessage() {}

func (x *FavoriteInfo) ProtoReflect() protoreflect.Message {
	mi := &file___proto_LibraryState_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteInfo.ProtoReflect.Descriptor instead.
func (*FavoriteInfo) Descriptor() ([]byte, []int) {
	return file___proto_LibraryState_proto_rawDescGZIP(), []int{8}
}

func (x *FavoriteInfo) GetStatus() uint64 {
	if x != nil {
		return x.Status
	}
	return 0
}

// QuotaInfo contains storage quota information
type QuotaInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field 1: Unknown
	QuotaChargedBytes uint64 `protobuf:"varint,2,opt,name=quota_charged_bytes,json=quotaChargedBytes,proto3" json:"quota_charged_bytes,omitempty"` // Bytes charged against quota
	QualityType       uint64 `protobuf:"varint,3,opt,name=quality_type,json=qualityType,proto3" json:"quality_type,omitempty"`                     // 2=original quality
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QuotaInfo) Reset() {
	*x = QuotaInfo{}
	mi := &file___proto_LibraryState_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaInfo) ProtoMessage() {}

func (x *QuotaInfo) ProtoReflect() protoreflect.Message {
	mi := &file___proto_LibraryState_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaInfo.ProtoReflect.Descriptor instead.
func (*QuotaInfo) Descriptor() ([]byte, []int) {
	return file___proto_LibraryState_proto_rawDescGZIP(), []int{9}
}

func (x *QuotaInfo) GetQuotaChargedBytes() uint64 {
	if x != nil {
		return x.QuotaChargedBytes
	}
	return 0
}

func (x *QuotaInfo) GetQualityType() uint64 {
	if x != nil {
		return x.QualityType
	}
	return 0
}

// LockInfo contains lock status
type LockInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        uint64                 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` // 1=locked
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockInfo) Reset() {
	*x = LockInfo{}
	mi := &file___proto_LibraryState_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockInfo) ProtoMessage() {}

func (x *LockInfo) ProtoReflect() protoreflect.Message {
	mi := &file___proto_LibraryState_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockInfo.ProtoReflect.Descriptor instead.
func (*LockInfo) Descriptor() ([]byte, []int) {
	return file___proto_LibraryState_proto_rawDescGZIP(), []int{10}
}

func (x *LockInfo) GetStatus() uint64 {
	if x != nil {
		return x.Status
	}
	return 0
}

// MediaTypeInfo contains type and format details
type MediaTypeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaType     uint64                 `protobuf:"varint,1,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"` // 1=photo, 2=video
	Photo         *PhotoInfo             `protobuf:"bytes,2,opt,name=photo,proto3" json:"photo,omitempty"`                           // Photo-specific info
	Video         *VideoInfo             `protobuf:"bytes,3,opt,name=video,proto3" json:"video,omitempty"`                           // Video-specific info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaTypeInfo) Reset() {
	*x = MediaTypeInfo{}
	mi := &file___proto_LibraryState_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaTypeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaTypeInfo) ProtoMessage() {}

func (x *MediaTypeInfo) ProtoReflect() protoreflect.Message {
	mi := &file___proto_LibraryState_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaTypeInfo.ProtoReflect.Descriptor instead.
func (*MediaTypeInfo) Descriptor() ([]byte, []int) {
	return file___proto_LibraryState_proto_rawDescGZIP(), []int{11}
}

func (x *MediaTypeInfo) GetMediaType() uint64 {
	if x != nil {
		return x.MediaType
	}
	return 0
}

func (x *MediaTypeInfo) GetPhoto() *PhotoInfo {
	if x != nil {
		return x.Photo
	}
	return nil
}

func (x *MediaTypeInfo) GetVideo() *VideoInfo {
	if x != nil {
		return x.Video
	}
	return nil
}

// PhotoInfo contains photo-specific information
type PhotoInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Details       *PhotoDetails          `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"` // Photo details
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhotoInfo) Reset() {
	*x = PhotoInfo{}
	mi := &file___proto_LibraryState_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhotoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhotoInfo) ProtoMessage() {}

func (x *PhotoInfo) ProtoReflect() protoreflect.Message {
	mi := &file___proto_LibraryState_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhotoInfo.ProtoReflect.Descriptor instead.
func (*PhotoInfo) Descriptor() ([]byte, []int) {
	return file___proto_LibraryState_proto_rawDescGZIP(), []int{12}
}

func (x *PhotoInfo) GetDetails() *PhotoDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

// PhotoDetails contains photo dimension and URL info
type PhotoDetails struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ThumbnailUrl string                 `protobuf:"bytes,1,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"` // Thumbnail URL
	// Fields 2-8: Various metadata
	Dimensions    *PhotoDimensions `protobuf:"bytes,9,opt,name=dimensions,proto3" json:"dimensions,omitempty"` // Width/height
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhotoDetails) Reset() {
	*x = PhotoDetails{}
	mi := &file___proto_LibraryState_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhotoDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhotoDetails) ProtoMessage() {}

func (x *PhotoDetails) ProtoReflect() protoreflect.Message {
	mi := &file___proto_LibraryState_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhotoDetails.ProtoReflect.Descriptor instead.
func (*PhotoDetails) Descriptor() ([]byte, []int) {
	return file___proto_LibraryState_proto_rawDescGZIP(), []int{13}
}

func (x *PhotoDetails) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *PhotoDetails) GetDimensions() *PhotoDimensions {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

// PhotoDimensions contains image dimensions
type PhotoDimensions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         uint64                 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint64                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"` // Field 5: Camera info (make, model, aperture, etc.)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhotoDimensions) Reset() {
	*x = PhotoDimensions{}
	mi := &file___proto_LibraryState_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhotoDimensions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhotoDimensions) ProtoMessage() {}

func (x *PhotoDimensions) ProtoReflect() protoreflect.Message {
	mi := &file___proto_LibraryState_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhotoDimensions.ProtoReflect.Descriptor instead.
func (*PhotoDimensions) Descriptor() ([]byte, []int) {
	return file___proto_LibraryState_proto_rawDescGZIP(), []int{14}
}

func (x *PhotoDimensions) GetWidth() uint64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *PhotoDimensions) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

// VideoInfo contains video-specific information
type VideoInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field 1: Unknown
	Thumbnail *VideoThumbnail `protobuf:"bytes,2,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"` // Thumbnail info
	// Field 3: Unknown
	Details       *VideoDetails `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`                            // Duration and dimensions
	DownloadUrl   string        `protobuf:"bytes,5,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"` // Download URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoInfo) Reset() {
	*x = VideoInfo{}
	mi := &file___proto_LibraryState_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoInfo) ProtoMessage() {}

func (x *VideoInfo) ProtoReflect() protoreflect.Message {
	mi := &file___proto_LibraryState_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoInfo.ProtoReflect.Descriptor instead.
func (*VideoInfo) Descriptor() ([]byte, []int) {
	return file___proto_LibraryState_proto_rawDescGZIP(), []int{15}
}

func (x *VideoInfo) GetThumbnail() *VideoThumbnail {
	if x != nil {
		return x.Thumbnail
	}
	return nil
}

func (x *VideoInfo) GetDetails() *VideoDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *VideoInfo) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

// VideoThumbnail contains video thumbnail URL
type VideoThumbnail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoThumbnail) Reset() {
	*x = VideoThumbnail{}
	mi := &file___proto_LibraryState_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoThumbnail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoThumbnail) ProtoMessage() {}

func (x *VideoThumbnail) ProtoReflect() protoreflect.Message {
	mi := &file___proto_LibraryState_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoThumbnail.ProtoReflect.Descriptor instead.
func (*VideoThumbnail) Descriptor() ([]byte, []int) {
	return file___proto_LibraryState_proto_rawDescGZIP(), []int{16}
}

func (x *VideoThumbnail) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// VideoDetails contains video duration and dimensions
type VideoDetails struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	DurationMs uint64                 `protobuf:"varint,1,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"` // Duration in milliseconds
	// Fields 2-3: Unknown
	Width         uint64 `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint64 `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoDetails) Reset() {
	*x = VideoDetails{}
	mi := &file___proto_LibraryState_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoDetails) ProtoMessage() {}

func (x *VideoDetails) ProtoReflect() protoreflect.Message {
	mi := &file___proto_LibraryState_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoDetails.ProtoReflect.Descriptor instead.
func (*VideoDetails) Descriptor() ([]byte, []int) {
	return file___proto_LibraryState_proto_rawDescGZIP(), []int{17}
}

func (x *VideoDetails) GetDurationMs() uint64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *VideoDetails) GetWidth() uint64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *VideoDetails) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

// MediaKeyInfo contains alternative media key
type MediaKeyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaKey      string                 `protobuf:"bytes,1,opt,name=media_key,json=mediaKey,proto3" json:"media_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaKeyInfo) Reset() {
	*x = MediaKeyInfo{}
	mi := &file___proto_LibraryState_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaKeyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaKeyInfo) ProtoMessage() {}

func (x *MediaKeyInfo) ProtoReflect() protoreflect.Message {
	mi := &file___proto_LibraryState_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaKeyInfo.ProtoReflect.Descriptor instead.
func (*MediaKeyInfo) Descriptor() ([]byte, []int) {
	return file___proto_LibraryState_proto_rawDescGZIP(), []int{18}
}

func (x *MediaKeyInfo) GetMediaKey() string {
	if x != nil {
		return x.MediaKey
	}
	return ""
}

// AlbumData represents an album/collection
type AlbumData struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	AlbumKey string                 `protobuf:"bytes,1,opt,name=album_key,json=albumKey,proto3" json:"album_key,omitempty"` // Album's unique key
	Metadata *AlbumMetadata         `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`                 // Album metadata
	// Field 4: Owner info
	// Field 5: Cover info
	SortInfo      *AlbumSortInfo `protobuf:"bytes,19,opt,name=sort_info,json=sortInfo,proto3" json:"sort_info,omitempty"` // Sort order info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlbumData) Reset() {
	*x = AlbumData{}
	mi := &file___proto_LibraryState_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlbumData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlbumData) ProtoMessage() {}

func (x *AlbumData) ProtoReflect() protoreflect.Message {
	mi := &file___proto_LibraryState_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlbumData.ProtoReflect.Descriptor instead.
func (*AlbumData) Descriptor() ([]byte, []int) {
	return file___proto_LibraryState_proto_rawDescGZIP(), []int{19}
}

func (x *AlbumData) GetAlbumKey() string {
	if x != nil {
		return x.AlbumKey
	}
	return ""
}

func (x *AlbumData) GetMetadata() *AlbumMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AlbumData) GetSortInfo() *AlbumSortInfo {
	if x != nil {
		return x.SortInfo
	}
	return nil
}

// AlbumMetadata contains album metadata
type AlbumMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field 1: Unknown
	// Field 3: Cover item key info
	// Field 4: Cover item key info (duplicate)
	Title string `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"` // Album title
	// Field 7: Total items (always 0 from server, calculate from media items)
	AlbumType uint64 `protobuf:"varint,8,opt,name=album_type,json=albumType,proto3" json:"album_type,omitempty"` // 1=user album
	// Field 10: Time range info
	// Field 11: Properties
	// Field 12: Unknown
	// Field 13: Unknown
	// Field 14: Unknown
	// Field 15: Cover URL
	CoverItem     *CoverItemInfo `protobuf:"bytes,17,opt,name=cover_item,json=coverItem,proto3" json:"cover_item,omitempty"` // Cover media item
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlbumMetadata) Reset() {
	*x = AlbumMetadata{}
	mi := &file___proto_LibraryState_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlbumMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlbumMetadata) ProtoMessage() {}

func (x *AlbumMetadata) ProtoReflect() protoreflect.Message {
	mi := &file___proto_LibraryState_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlbumMetadata.ProtoReflect.Descriptor instead.
func (*AlbumMetadata) Descriptor() ([]byte, []int) {
	return file___proto_LibraryState_proto_rawDescGZIP(), []int{20}
}

func (x *AlbumMetadata) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AlbumMetadata) GetAlbumType() uint64 {
	if x != nil {
		return x.AlbumType
	}
	return 0
}

func (x *AlbumMetadata) GetCoverItem() *CoverItemInfo {
	if x != nil {
		return x.CoverItem
	}
	return nil
}

// CoverItemInfo contains album cover information
type CoverItemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaKey      string                 `protobuf:"bytes,1,opt,name=media_key,json=mediaKey,proto3" json:"media_key,omitempty"` // Cover item's media key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoverItemInfo) Reset() {
	*x = CoverItemInfo{}
	mi := &file___proto_LibraryState_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoverItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoverItemInfo) ProtoMessage() {}

func (x *CoverItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file___proto_LibraryState_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoverItemInfo.ProtoReflect.Descriptor instead.
func (*CoverItemInfo) Descriptor() ([]byte, []int) {
	return file___proto_LibraryState_proto_rawDescGZIP(), []int{21}
}

func (x *CoverItemInfo) GetMediaKey() string {
	if x != nil {
		return x.MediaKey
	}
	return ""
}

// AlbumSortInfo contains album sort order
type AlbumSortInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SortOrder       uint64                 `protobuf:"varint,1,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`                     // Sort order value
	IsCustomOrdered uint64                 `protobuf:"varint,2,opt,name=is_custom_ordered,json=isCustomOrdered,proto3" json:"is_custom_ordered,omitempty"` // 1=custom ordered
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AlbumSortInfo) Reset() {
	*x = AlbumSortInfo{}
	mi := &file___proto_LibraryState_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlbumSortInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlbumSortInfo) ProtoMessage() {}

func (x *AlbumSortInfo) ProtoReflect() protoreflect.Message {
	mi := &file___proto_LibraryState_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlbumSortInfo.ProtoReflect.Descriptor instead.
func (*AlbumSortInfo) Descriptor() ([]byte, []int) {
	return file___proto_LibraryState_proto_rawDescGZIP(), []int{22}
}

func (x *AlbumSortInfo) GetSortOrder() uint64 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *AlbumSortInfo) GetIsCustomOrdered() uint64 {
	if x != nil {
		return x.IsCustomOrdered
	}
	return 0
}

// DeletionData represents a deleted item marker
type DeletionData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *DeletionInfo          `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletionData) Reset() {
	*x = DeletionData{}
	mi := &file___proto_LibraryState_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletionData) ProtoMessage() {}

func (x *DeletionData) ProtoReflect() protoreflect.Message {
	mi := &file___proto_LibraryState_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletionData.ProtoReflect.Descriptor instead.
func (*DeletionData) Descriptor() ([]byte, []int) {
	return file___proto_LibraryState_proto_rawDescGZIP(), []int{23}
}

func (x *DeletionData) GetInfo() *DeletionInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// DeletionInfo contains deletion details
type DeletionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletionType  uint64                 `protobuf:"varint,1,opt,name=deletion_type,json=deletionType,proto3" json:"deletion_type,omitempty"` // 1=media item deletion
	Media         *DeletedMediaInfo      `protobuf:"bytes,2,opt,name=media,proto3" json:"media,omitempty"`                                    // Deleted media info (when type=1)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletionInfo) Reset() {
	*x = DeletionInfo{}
	mi := &file___proto_LibraryState_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletionInfo) ProtoMessage() {}

func (x *DeletionInfo) ProtoReflect() protoreflect.Message {
	mi := &file___proto_LibraryState_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletionInfo.ProtoReflect.Descriptor instead.
func (*DeletionInfo) Descriptor() ([]byte, []int) {
	return file___proto_LibraryState_proto_rawDescGZIP(), []int{24}
}

func (x *DeletionInfo) GetDeletionType() uint64 {
	if x != nil {
		return x.DeletionType
	}
	return 0
}

func (x *DeletionInfo) GetMedia() *DeletedMediaInfo {
	if x != nil {
		return x.Media
	}
	return nil
}

// DeletedMediaInfo contains deleted media key
type DeletedMediaInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaKey      string                 `protobuf:"bytes,1,opt,name=media_key,json=mediaKey,proto3" json:"media_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletedMediaInfo) Reset() {
	*x = DeletedMediaInfo{}
	mi := &file___proto_LibraryState_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletedMediaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletedMediaInfo) ProtoMessage() {}

func (x *DeletedMediaInfo) ProtoReflect() protoreflect.Message {
	mi := &file___proto_LibraryState_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletedMediaInfo.ProtoReflect.Descriptor instead.
func (*DeletedMediaInfo) Descriptor() ([]byte, []int) {
	return file___proto_LibraryState_proto_rawDescGZIP(), []int{25}
}

func (x *DeletedMediaInfo) GetMediaKey() string {
	if x != nil {
		return x.MediaKey
	}
	return ""
}

var File___proto_LibraryState_proto protoreflect.FileDescriptor

const file___proto_LibraryState_proto_rawDesc = "" +
	"\n" +
	"\x19.proto/LibraryState.proto\x12\x03gpm\"A\n" +
	"\x14LibraryStateResponse\x12)\n" +
	"\x04data\x18\x01 \x01(\v2\x15.gpm.LibraryStateDataR\x04data\"\xe9\x01\n" +
	"\x10LibraryStateData\x12&\n" +
	"\x0fnext_page_token\x18\x01 \x01(\tR\rnextPageToken\x123\n" +
	"\vmedia_items\x18\x02 \x03(\v2\x12.gpm.MediaItemDataR\n" +
	"mediaItems\x12&\n" +
	"\x06albums\x18\x03 \x03(\v2\x0e.gpm.AlbumDataR\x06albums\x12\x1f\n" +
	"\vstate_token\x18\x06 \x01(\tR\n" +
	"stateToken\x12/\n" +
	"\tdeletions\x18\t \x03(\v2\x11.gpm.DeletionDataR\tdeletions\"\xbb\x01\n" +
	"\rMediaItemData\x12\x1b\n" +
	"\tmedia_key\x18\x01 \x01(\tR\bmediaKey\x12.\n" +
	"\bmetadata\x18\x02 \x01(\v2\x12.gpm.MediaMetadataR\bmetadata\x12/\n" +
	"\ttype_info\x18\x05 \x01(\v2\x12.gpm.MediaTypeInfoR\btypeInfo\x12,\n" +
	"\bkey_info\x18\x06 \x01(\v2\x11.gpm.MediaKeyInfoR\akeyInfo\"\xd5\x04\n" +
	"\rMediaMetadata\x123\n" +
	"\n" +
	"collection\x18\x01 \x01(\v2\x13.gpm.CollectionInfoR\n" +
	"collection\x12\x1b\n" +
	"\tfile_name\x18\x04 \x01(\tR\bfileName\x121\n" +
	"\n" +
	"properties\x18\x05 \x03(\v2\x11.gpm.PropertyInfoR\n" +
	"properties\x12#\n" +
	"\rutc_timestamp\x18\a \x01(\x04R\futcTimestamp\x12'\n" +
	"\x0ftimezone_offset\x18\b \x01(\x04R\x0etimezoneOffset\x12:\n" +
	"\x19server_creation_timestamp\x18\t \x01(\x04R\x17serverCreationTimestamp\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\n" +
	" \x01(\x04R\tsizeBytes\x12#\n" +
	"\rupload_status\x18\v \x01(\x04R\fuploadStatus\x12$\n" +
	"\x05dedup\x18\x15 \x01(\v2\x0e.gpm.DedupInfoR\x05dedup\x12'\n" +
	"\x0fcontent_version\x18\x1a \x01(\x04R\x0econtentVersion\x12*\n" +
	"\aarchive\x18\x1d \x01(\v2\x10.gpm.ArchiveInfoR\aarchive\x12-\n" +
	"\bfavorite\x18\x1f \x01(\v2\x11.gpm.FavoriteInfoR\bfavorite\x12$\n" +
	"\x05quota\x18# \x01(\v2\x0e.gpm.QuotaInfoR\x05quota\x12!\n" +
	"\x04lock\x18' \x01(\v2\r.gpm.LockInfoR\x04lock\"5\n" +
	"\x0eCollectionInfo\x12#\n" +
	"\rcollection_id\x18\x01 \x01(\tR\fcollectionId\"/\n" +
	"\fPropertyInfo\x12\x1f\n" +
	"\vproperty_id\x18\x01 \x01(\x04R\n" +
	"propertyId\"(\n" +
	"\tDedupInfo\x12\x1b\n" +
	"\tdedup_key\x18\x01 \x01(\tR\bdedupKey\"%\n" +
	"\vArchiveInfo\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x04R\x06status\"&\n" +
	"\fFavoriteInfo\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x04R\x06status\"^\n" +
	"\tQuotaInfo\x12.\n" +
	"\x13quota_charged_bytes\x18\x02 \x01(\x04R\x11quotaChargedBytes\x12!\n" +
	"\fquality_type\x18\x03 \x01(\x04R\vqualityType\"\"\n" +
	"\bLockInfo\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x04R\x06status\"z\n" +
	"\rMediaTypeInfo\x12\x1d\n" +
	"\n" +
	"media_type\x18\x01 \x01(\x04R\tmediaType\x12$\n" +
	"\x05photo\x18\x02 \x01(\v2\x0e.gpm.PhotoInfoR\x05photo\x12$\n" +
	"\x05video\x18\x03 \x01(\v2\x0e.gpm.VideoInfoR\x05video\"8\n" +
	"\tPhotoInfo\x12+\n" +
	"\adetails\x18\x01 \x01(\v2\x11.gpm.PhotoDetailsR\adetails\"i\n" +
	"\fPhotoDetails\x12#\n" +
	"\rthumbnail_url\x18\x01 \x01(\tR\fthumbnailUrl\x124\n" +
	"\n" +
	"dimensions\x18\t \x01(\v2\x14.gpm.PhotoDimensionsR\n" +
	"dimensions\"?\n" +
	"\x0fPhotoDimensions\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x04R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height\"\x8e\x01\n" +
	"\tVideoInfo\x121\n" +
	"\tthumbnail\x18\x02 \x01(\v2\x13.gpm.VideoThumbnailR\tthumbnail\x12+\n" +
	"\adetails\x18\x04 \x01(\v2\x11.gpm.VideoDetailsR\adetails\x12!\n" +
	"\fdownload_url\x18\x05 \x01(\tR\vdownloadUrl\"\"\n" +
	"\x0eVideoThumbnail\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"]\n" +
	"\fVideoDetails\x12\x1f\n" +
	"\vduration_ms\x18\x01 \x01(\x04R\n" +
	"durationMs\x12\x14\n" +
	"\x05width\x18\x04 \x01(\x04R\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x04R\x06height\"+\n" +
	"\fMediaKeyInfo\x12\x1b\n" +
	"\tmedia_key\x18\x01 \x01(\tR\bmediaKey\"\x89\x01\n" +
	"\tAlbumData\x12\x1b\n" +
	"\talbum_key\x18\x01 \x01(\tR\balbumKey\x12.\n" +
	"\bmetadata\x18\x02 \x01(\v2\x12.gpm.AlbumMetadataR\bmetadata\x12/\n" +
	"\tsort_info\x18\x13 \x01(\v2\x12.gpm.AlbumSortInfoR\bsortInfo\"w\n" +
	"\rAlbumMetadata\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"album_type\x18\b \x01(\x04R\talbumType\x121\n" +
	"\n" +
	"cover_item\x18\x11 \x01(\v2\x12.gpm.CoverItemInfoR\tcoverItem\",\n" +
	"\rCoverItemInfo\x12\x1b\n" +
	"\tmedia_key\x18\x01 \x01(\tR\bmediaKey\"Z\n" +
	"\rAlbumSortInfo\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x01 \x01(\x04R\tsortOrder\x12*\n" +
	"\x11is_custom_ordered\x18\x02 \x01(\x04R\x0fisCustomOrdered\"5\n" +
	"\fDeletionData\x12%\n" +
	"\x04info\x18\x01 \x01(\v2\x11.gpm.DeletionInfoR\x04info\"`\n" +
	"\fDeletionInfo\x12#\n" +
	"\rdeletion_type\x18\x01 \x01(\x04R\fdeletionType\x12+\n" +
	"\x05media\x18\x02 \x01(\v2\x15.gpm.DeletedMediaInfoR\x05media\"/\n" +
	"\x10DeletedMediaInfo\x12\x1b\n" +
	"\tmedia_key\x18\x01 \x01(\tR\bmediaKeyB.Z,github.com/viperadnan-git/go-gpm/internal/pbb\x06proto3"

var (
	file___proto_LibraryState_proto_rawDescOnce sync.Once
	file___proto_LibraryState_proto_rawDescData []byte
)

func file___proto_LibraryState_proto_rawDescGZIP() []byte {
	file___proto_LibraryState_proto_rawDescOnce.Do(func() {
		file___proto_LibraryState_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file___proto_LibraryState_proto_rawDesc), len(file___proto_LibraryState_proto_rawDesc)))
	})
	return file___proto_LibraryState_proto_rawDescData
}

var file___proto_LibraryState_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file___proto_LibraryState_proto_goTypes = []any{
	(*LibraryStateResponse)(nil), // 0: gpm.LibraryStateResponse
	(*LibraryStateData)(nil),     // 1: gpm.LibraryStateData
	(*MediaItemData)(nil),        // 2: gpm.MediaItemData
	(*MediaMetadata)(nil),        // 3: gpm.MediaMetadata
	(*CollectionInfo)(nil),       // 4: gpm.CollectionInfo
	(*PropertyInfo)(nil),         // 5: gpm.PropertyInfo
	(*DedupInfo)(nil),            // 6: gpm.DedupInfo
	(*ArchiveInfo)(nil),          // 7: gpm.ArchiveInfo
	(*FavoriteInfo)(nil),         // 8: gpm.FavoriteInfo
	(*QuotaInfo)(nil),            // 9: gpm.QuotaInfo
	(*LockInfo)(nil),             // 10: gpm.LockInfo
	(*MediaTypeInfo)(nil),        // 11: gpm.MediaTypeInfo
	(*PhotoInfo)(nil),            // 12: gpm.PhotoInfo
	(*PhotoDetails)(nil),         // 13: gpm.PhotoDetails
	(*PhotoDimensions)(nil),      // 14: gpm.PhotoDimensions
	(*VideoInfo)(nil),            // 15: gpm.VideoInfo
	(*VideoThumbnail)(nil),       // 16: gpm.VideoThumbnail
	(*VideoDetails)(nil),         // 17: gpm.VideoDetails
	(*MediaKeyInfo)(nil),         // 18: gpm.MediaKeyInfo
	(*AlbumData)(nil),            // 19: gpm.AlbumData
	(*AlbumMetadata)(nil),        // 20: gpm.AlbumMetadata
	(*CoverItemInfo)(nil),        // 21: gpm.CoverItemInfo
	(*AlbumSortInfo)(nil),        // 22: gpm.AlbumSortInfo
	(*DeletionData)(nil),         // 23: gpm.DeletionData
	(*DeletionInfo)(nil),         // 24: gpm.DeletionInfo
	(*DeletedMediaInfo)(nil),     // 25: gpm.DeletedMediaInfo
}
var file___proto_LibraryState_proto_depIdxs = []int32{
	1,  // 0: gpm.LibraryStateResponse.data:type_name -> gpm.LibraryStateData
	2,  // 1: gpm.LibraryStateData.media_items:type_name -> gpm.MediaItemData
	19, // 2: gpm.LibraryStateData.albums:type_name -> gpm.AlbumData
	23, // 3: gpm.LibraryStateData.deletions:type_name -> gpm.DeletionData
	3,  // 4: gpm.MediaItemData.metadata:type_name -> gpm.MediaMetadata
	11, // 5: gpm.MediaItemData.type_info:type_name -> gpm.MediaTypeInfo
	18, // 6: gpm.MediaItemData.key_info:type_name -> gpm.MediaKeyInfo
	4,  // 7: gpm.MediaMetadata.collection:type_name -> gpm.CollectionInfo
	5,  // 8: gpm.MediaMetadata.properties:type_name -> gpm.PropertyInfo
	6,  // 9: gpm.MediaMetadata.dedup:type_name -> gpm.DedupInfo
	7,  // 10: gpm.MediaMetadata.archive:type_name -> gpm.ArchiveInfo
	8,  // 11: gpm.MediaMetadata.favorite:type_name -> gpm.FavoriteInfo
	9,  // 12: gpm.MediaMetadata.quota:type_name -> gpm.QuotaInfo
	10, // 13: gpm.MediaMetadata.lock:type_name -> gpm.LockInfo
	12, // 14: gpm.MediaTypeInfo.photo:type_name -> gpm.PhotoInfo
	15, // 15: gpm.MediaTypeInfo.video:type_name -> gpm.VideoInfo
	13, // 16: gpm.PhotoInfo.details:type_name -> gpm.PhotoDetails
	14, // 17: gpm.PhotoDetails.dimensions:type_name -> gpm.PhotoDimensions
	16, // 18: gpm.VideoInfo.thumbnail:type_name -> gpm.VideoThumbnail
	17, // 19: gpm.VideoInfo.details:type_name -> gpm.VideoDetails
	20, // 20: gpm.AlbumData.metadata:type_name -> gpm.AlbumMetadata
	22, // 21: gpm.AlbumData.sort_info:type_name -> gpm.AlbumSortInfo
	21, // 22: gpm.AlbumMetadata.cover_item:type_name -> gpm.CoverItemInfo
	24, // 23: gpm.DeletionData.info:type_name -> gpm.DeletionInfo
	25, // 24: gpm.DeletionInfo.media:type_name -> gpm.DeletedMediaInfo
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file___proto_LibraryState_proto_init() }
func file___proto_LibraryState_proto_init() {
	if File___proto_LibraryState_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file___proto_LibraryState_proto_rawDesc), len(file___proto_LibraryState_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file___proto_LibraryState_proto_goTypes,
		DependencyIndexes: file___proto_LibraryState_proto_depIdxs,
		MessageInfos:      file___proto_LibraryState_proto_msgTypes,
	}.Build()
	File___proto_LibraryState_proto = out.File
	file___proto_LibraryState_proto_goTypes = nil
	file___proto_LibraryState_proto_depIdxs = nil
}
