// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: .proto/MoveToTrash.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MoveToTrash struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field2        int64                  `protobuf:"varint,2,opt,name=field2,proto3" json:"field2,omitempty"` // constant: 1
	ItemKeys      []string               `protobuf:"bytes,3,rep,name=item_keys,json=itemKeys,proto3" json:"item_keys,omitempty"`
	Field4        int64                  `protobuf:"varint,4,opt,name=field4,proto3" json:"field4,omitempty"` // constant: 1
	Field8        *MoveToTrash_Field8    `protobuf:"bytes,8,opt,name=field8,proto3" json:"field8,omitempty"`
	Field9        *MoveToTrash_Field9    `protobuf:"bytes,9,opt,name=field9,proto3" json:"field9,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveToTrash) Reset() {
	*x = MoveToTrash{}
	mi := &file___proto_MoveToTrash_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveToTrash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveToTrash) ProtoMessage() {}

func (x *MoveToTrash) ProtoReflect() protoreflect.Message {
	mi := &file___proto_MoveToTrash_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveToTrash.ProtoReflect.Descriptor instead.
func (*MoveToTrash) Descriptor() ([]byte, []int) {
	return file___proto_MoveToTrash_proto_rawDescGZIP(), []int{0}
}

func (x *MoveToTrash) GetField2() int64 {
	if x != nil {
		return x.Field2
	}
	return 0
}

func (x *MoveToTrash) GetItemKeys() []string {
	if x != nil {
		return x.ItemKeys
	}
	return nil
}

func (x *MoveToTrash) GetField4() int64 {
	if x != nil {
		return x.Field4
	}
	return 0
}

func (x *MoveToTrash) GetField8() *MoveToTrash_Field8 {
	if x != nil {
		return x.Field8
	}
	return nil
}

func (x *MoveToTrash) GetField9() *MoveToTrash_Field9 {
	if x != nil {
		return x.Field9
	}
	return nil
}

type MoveToTrash_Field8 struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Field4        *MoveToTrash_Field8_Field4 `protobuf:"bytes,4,opt,name=field4,proto3" json:"field4,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveToTrash_Field8) Reset() {
	*x = MoveToTrash_Field8{}
	mi := &file___proto_MoveToTrash_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveToTrash_Field8) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveToTrash_Field8) ProtoMessage() {}

func (x *MoveToTrash_Field8) ProtoReflect() protoreflect.Message {
	mi := &file___proto_MoveToTrash_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveToTrash_Field8.ProtoReflect.Descriptor instead.
func (*MoveToTrash_Field8) Descriptor() ([]byte, []int) {
	return file___proto_MoveToTrash_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MoveToTrash_Field8) GetField4() *MoveToTrash_Field8_Field4 {
	if x != nil {
		return x.Field4
	}
	return nil
}

type MoveToTrash_Field9 struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Field1        int64                      `protobuf:"varint,1,opt,name=field1,proto3" json:"field1,omitempty"` // constant: 5
	Field2        *MoveToTrash_Field9_Field2 `protobuf:"bytes,2,opt,name=field2,proto3" json:"field2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveToTrash_Field9) Reset() {
	*x = MoveToTrash_Field9{}
	mi := &file___proto_MoveToTrash_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveToTrash_Field9) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveToTrash_Field9) ProtoMessage() {}

func (x *MoveToTrash_Field9) ProtoReflect() protoreflect.Message {
	mi := &file___proto_MoveToTrash_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveToTrash_Field9.ProtoReflect.Descriptor instead.
func (*MoveToTrash_Field9) Descriptor() ([]byte, []int) {
	return file___proto_MoveToTrash_proto_rawDescGZIP(), []int{0, 1}
}

func (x *MoveToTrash_Field9) GetField1() int64 {
	if x != nil {
		return x.Field1
	}
	return 0
}

func (x *MoveToTrash_Field9) GetField2() *MoveToTrash_Field9_Field2 {
	if x != nil {
		return x.Field2
	}
	return nil
}

type MoveToTrash_Field8_Field4 struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Field2        *MoveToTrash_Field8_Field4_Empty  `protobuf:"bytes,2,opt,name=field2,proto3" json:"field2,omitempty"`
	Field3        *MoveToTrash_Field8_Field4_Field3 `protobuf:"bytes,3,opt,name=field3,proto3" json:"field3,omitempty"`
	Field4        *MoveToTrash_Field8_Field4_Empty  `protobuf:"bytes,4,opt,name=field4,proto3" json:"field4,omitempty"`
	Field5        *MoveToTrash_Field8_Field4_Field5 `protobuf:"bytes,5,opt,name=field5,proto3" json:"field5,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveToTrash_Field8_Field4) Reset() {
	*x = MoveToTrash_Field8_Field4{}
	mi := &file___proto_MoveToTrash_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveToTrash_Field8_Field4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveToTrash_Field8_Field4) ProtoMessage() {}

func (x *MoveToTrash_Field8_Field4) ProtoReflect() protoreflect.Message {
	mi := &file___proto_MoveToTrash_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveToTrash_Field8_Field4.ProtoReflect.Descriptor instead.
func (*MoveToTrash_Field8_Field4) Descriptor() ([]byte, []int) {
	return file___proto_MoveToTrash_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *MoveToTrash_Field8_Field4) GetField2() *MoveToTrash_Field8_Field4_Empty {
	if x != nil {
		return x.Field2
	}
	return nil
}

func (x *MoveToTrash_Field8_Field4) GetField3() *MoveToTrash_Field8_Field4_Field3 {
	if x != nil {
		return x.Field3
	}
	return nil
}

func (x *MoveToTrash_Field8_Field4) GetField4() *MoveToTrash_Field8_Field4_Empty {
	if x != nil {
		return x.Field4
	}
	return nil
}

func (x *MoveToTrash_Field8_Field4) GetField5() *MoveToTrash_Field8_Field4_Field5 {
	if x != nil {
		return x.Field5
	}
	return nil
}

type MoveToTrash_Field8_Field4_Field3 struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Field1        *MoveToTrash_Field8_Field4_Empty `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveToTrash_Field8_Field4_Field3) Reset() {
	*x = MoveToTrash_Field8_Field4_Field3{}
	mi := &file___proto_MoveToTrash_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveToTrash_Field8_Field4_Field3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveToTrash_Field8_Field4_Field3) ProtoMessage() {}

func (x *MoveToTrash_Field8_Field4_Field3) ProtoReflect() protoreflect.Message {
	mi := &file___proto_MoveToTrash_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveToTrash_Field8_Field4_Field3.ProtoReflect.Descriptor instead.
func (*MoveToTrash_Field8_Field4_Field3) Descriptor() ([]byte, []int) {
	return file___proto_MoveToTrash_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

func (x *MoveToTrash_Field8_Field4_Field3) GetField1() *MoveToTrash_Field8_Field4_Empty {
	if x != nil {
		return x.Field1
	}
	return nil
}

type MoveToTrash_Field8_Field4_Field5 struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Field1        *MoveToTrash_Field8_Field4_Empty `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveToTrash_Field8_Field4_Field5) Reset() {
	*x = MoveToTrash_Field8_Field4_Field5{}
	mi := &file___proto_MoveToTrash_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveToTrash_Field8_Field4_Field5) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveToTrash_Field8_Field4_Field5) ProtoMessage() {}

func (x *MoveToTrash_Field8_Field4_Field5) ProtoReflect() protoreflect.Message {
	mi := &file___proto_MoveToTrash_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveToTrash_Field8_Field4_Field5.ProtoReflect.Descriptor instead.
func (*MoveToTrash_Field8_Field4_Field5) Descriptor() ([]byte, []int) {
	return file___proto_MoveToTrash_proto_rawDescGZIP(), []int{0, 0, 0, 1}
}

func (x *MoveToTrash_Field8_Field4_Field5) GetField1() *MoveToTrash_Field8_Field4_Empty {
	if x != nil {
		return x.Field1
	}
	return nil
}

type MoveToTrash_Field8_Field4_Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveToTrash_Field8_Field4_Empty) Reset() {
	*x = MoveToTrash_Field8_Field4_Empty{}
	mi := &file___proto_MoveToTrash_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveToTrash_Field8_Field4_Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveToTrash_Field8_Field4_Empty) ProtoMessage() {}

func (x *MoveToTrash_Field8_Field4_Empty) ProtoReflect() protoreflect.Message {
	mi := &file___proto_MoveToTrash_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveToTrash_Field8_Field4_Empty.ProtoReflect.Descriptor instead.
func (*MoveToTrash_Field8_Field4_Empty) Descriptor() ([]byte, []int) {
	return file___proto_MoveToTrash_proto_rawDescGZIP(), []int{0, 0, 0, 2}
}

type MoveToTrash_Field9_Field2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field1        int64                  `protobuf:"varint,1,opt,name=field1,proto3" json:"field1,omitempty"` // client_version_code
	Field2        string                 `protobuf:"bytes,2,opt,name=field2,proto3" json:"field2,omitempty"`  // android_api_version as string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveToTrash_Field9_Field2) Reset() {
	*x = MoveToTrash_Field9_Field2{}
	mi := &file___proto_MoveToTrash_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveToTrash_Field9_Field2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveToTrash_Field9_Field2) ProtoMessage() {}

func (x *MoveToTrash_Field9_Field2) ProtoReflect() protoreflect.Message {
	mi := &file___proto_MoveToTrash_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveToTrash_Field9_Field2.ProtoReflect.Descriptor instead.
func (*MoveToTrash_Field9_Field2) Descriptor() ([]byte, []int) {
	return file___proto_MoveToTrash_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *MoveToTrash_Field9_Field2) GetField1() int64 {
	if x != nil {
		return x.Field1
	}
	return 0
}

func (x *MoveToTrash_Field9_Field2) GetField2() string {
	if x != nil {
		return x.Field2
	}
	return ""
}

var File___proto_MoveToTrash_proto protoreflect.FileDescriptor

const file___proto_MoveToTrash_proto_rawDesc = "" +
	"\n" +
	"\x18.proto/MoveToTrash.proto\"\x8a\x06\n" +
	"\vMoveToTrash\x12\x16\n" +
	"\x06field2\x18\x02 \x01(\x03R\x06field2\x12\x1b\n" +
	"\titem_keys\x18\x03 \x03(\tR\bitemKeys\x12\x16\n" +
	"\x06field4\x18\x04 \x01(\x03R\x06field4\x12+\n" +
	"\x06field8\x18\b \x01(\v2\x13.MoveToTrash.Field8R\x06field8\x12+\n" +
	"\x06field9\x18\t \x01(\v2\x13.MoveToTrash.Field9R\x06field9\x1a\xc2\x03\n" +
	"\x06Field8\x122\n" +
	"\x06field4\x18\x04 \x01(\v2\x1a.MoveToTrash.Field8.Field4R\x06field4\x1a\x83\x03\n" +
	"\x06Field4\x128\n" +
	"\x06field2\x18\x02 \x01(\v2 .MoveToTrash.Field8.Field4.EmptyR\x06field2\x129\n" +
	"\x06field3\x18\x03 \x01(\v2!.MoveToTrash.Field8.Field4.Field3R\x06field3\x128\n" +
	"\x06field4\x18\x04 \x01(\v2 .MoveToTrash.Field8.Field4.EmptyR\x06field4\x129\n" +
	"\x06field5\x18\x05 \x01(\v2!.MoveToTrash.Field8.Field4.Field5R\x06field5\x1aB\n" +
	"\x06Field3\x128\n" +
	"\x06field1\x18\x01 \x01(\v2 .MoveToTrash.Field8.Field4.EmptyR\x06field1\x1aB\n" +
	"\x06Field5\x128\n" +
	"\x06field1\x18\x01 \x01(\v2 .MoveToTrash.Field8.Field4.EmptyR\x06field1\x1a\a\n" +
	"\x05Empty\x1a\x8e\x01\n" +
	"\x06Field9\x12\x16\n" +
	"\x06field1\x18\x01 \x01(\x03R\x06field1\x122\n" +
	"\x06field2\x18\x02 \x01(\v2\x1a.MoveToTrash.Field9.Field2R\x06field2\x1a8\n" +
	"\x06Field2\x12\x16\n" +
	"\x06field1\x18\x01 \x01(\x03R\x06field1\x12\x16\n" +
	"\x06field2\x18\x02 \x01(\tR\x06field2B\x05Z\x03/pbb\x06proto3"

var (
	file___proto_MoveToTrash_proto_rawDescOnce sync.Once
	file___proto_MoveToTrash_proto_rawDescData []byte
)

func file___proto_MoveToTrash_proto_rawDescGZIP() []byte {
	file___proto_MoveToTrash_proto_rawDescOnce.Do(func() {
		file___proto_MoveToTrash_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file___proto_MoveToTrash_proto_rawDesc), len(file___proto_MoveToTrash_proto_rawDesc)))
	})
	return file___proto_MoveToTrash_proto_rawDescData
}

var file___proto_MoveToTrash_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file___proto_MoveToTrash_proto_goTypes = []any{
	(*MoveToTrash)(nil),                      // 0: MoveToTrash
	(*MoveToTrash_Field8)(nil),               // 1: MoveToTrash.Field8
	(*MoveToTrash_Field9)(nil),               // 2: MoveToTrash.Field9
	(*MoveToTrash_Field8_Field4)(nil),        // 3: MoveToTrash.Field8.Field4
	(*MoveToTrash_Field8_Field4_Field3)(nil), // 4: MoveToTrash.Field8.Field4.Field3
	(*MoveToTrash_Field8_Field4_Field5)(nil), // 5: MoveToTrash.Field8.Field4.Field5
	(*MoveToTrash_Field8_Field4_Empty)(nil),  // 6: MoveToTrash.Field8.Field4.Empty
	(*MoveToTrash_Field9_Field2)(nil),        // 7: MoveToTrash.Field9.Field2
}
var file___proto_MoveToTrash_proto_depIdxs = []int32{
	1,  // 0: MoveToTrash.field8:type_name -> MoveToTrash.Field8
	2,  // 1: MoveToTrash.field9:type_name -> MoveToTrash.Field9
	3,  // 2: MoveToTrash.Field8.field4:type_name -> MoveToTrash.Field8.Field4
	7,  // 3: MoveToTrash.Field9.field2:type_name -> MoveToTrash.Field9.Field2
	6,  // 4: MoveToTrash.Field8.Field4.field2:type_name -> MoveToTrash.Field8.Field4.Empty
	4,  // 5: MoveToTrash.Field8.Field4.field3:type_name -> MoveToTrash.Field8.Field4.Field3
	6,  // 6: MoveToTrash.Field8.Field4.field4:type_name -> MoveToTrash.Field8.Field4.Empty
	5,  // 7: MoveToTrash.Field8.Field4.field5:type_name -> MoveToTrash.Field8.Field4.Field5
	6,  // 8: MoveToTrash.Field8.Field4.Field3.field1:type_name -> MoveToTrash.Field8.Field4.Empty
	6,  // 9: MoveToTrash.Field8.Field4.Field5.field1:type_name -> MoveToTrash.Field8.Field4.Empty
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file___proto_MoveToTrash_proto_init() }
func file___proto_MoveToTrash_proto_init() {
	if File___proto_MoveToTrash_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file___proto_MoveToTrash_proto_rawDesc), len(file___proto_MoveToTrash_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file___proto_MoveToTrash_proto_goTypes,
		DependencyIndexes: file___proto_MoveToTrash_proto_depIdxs,
		MessageInfos:      file___proto_MoveToTrash_proto_msgTypes,
	}.Build()
	File___proto_MoveToTrash_proto = out.File
	file___proto_MoveToTrash_proto_goTypes = nil
	file___proto_MoveToTrash_proto_depIdxs = nil
}
