// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: .proto/RestoreFromTrash.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RestoreFromTrash struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Field2        int64                    `protobuf:"varint,2,opt,name=field2,proto3" json:"field2,omitempty"` // constant: 3
	ItemKeys      []string                 `protobuf:"bytes,3,rep,name=item_keys,json=itemKeys,proto3" json:"item_keys,omitempty"`
	Field4        int64                    `protobuf:"varint,4,opt,name=field4,proto3" json:"field4,omitempty"` // constant: 2
	Field8        *RestoreFromTrash_Field8 `protobuf:"bytes,8,opt,name=field8,proto3" json:"field8,omitempty"`
	Field9        *RestoreFromTrash_Field9 `protobuf:"bytes,9,opt,name=field9,proto3" json:"field9,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreFromTrash) Reset() {
	*x = RestoreFromTrash{}
	mi := &file___proto_RestoreFromTrash_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreFromTrash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreFromTrash) ProtoMessage() {}

func (x *RestoreFromTrash) ProtoReflect() protoreflect.Message {
	mi := &file___proto_RestoreFromTrash_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreFromTrash.ProtoReflect.Descriptor instead.
func (*RestoreFromTrash) Descriptor() ([]byte, []int) {
	return file___proto_RestoreFromTrash_proto_rawDescGZIP(), []int{0}
}

func (x *RestoreFromTrash) GetField2() int64 {
	if x != nil {
		return x.Field2
	}
	return 0
}

func (x *RestoreFromTrash) GetItemKeys() []string {
	if x != nil {
		return x.ItemKeys
	}
	return nil
}

func (x *RestoreFromTrash) GetField4() int64 {
	if x != nil {
		return x.Field4
	}
	return 0
}

func (x *RestoreFromTrash) GetField8() *RestoreFromTrash_Field8 {
	if x != nil {
		return x.Field8
	}
	return nil
}

func (x *RestoreFromTrash) GetField9() *RestoreFromTrash_Field9 {
	if x != nil {
		return x.Field9
	}
	return nil
}

type RestoreFromTrash_Field8 struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Field4        *RestoreFromTrash_Field8_Field4 `protobuf:"bytes,4,opt,name=field4,proto3" json:"field4,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreFromTrash_Field8) Reset() {
	*x = RestoreFromTrash_Field8{}
	mi := &file___proto_RestoreFromTrash_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreFromTrash_Field8) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreFromTrash_Field8) ProtoMessage() {}

func (x *RestoreFromTrash_Field8) ProtoReflect() protoreflect.Message {
	mi := &file___proto_RestoreFromTrash_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreFromTrash_Field8.ProtoReflect.Descriptor instead.
func (*RestoreFromTrash_Field8) Descriptor() ([]byte, []int) {
	return file___proto_RestoreFromTrash_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RestoreFromTrash_Field8) GetField4() *RestoreFromTrash_Field8_Field4 {
	if x != nil {
		return x.Field4
	}
	return nil
}

type RestoreFromTrash_Field9 struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Field1        int64                           `protobuf:"varint,1,opt,name=field1,proto3" json:"field1,omitempty"` // constant: 5
	Field2        *RestoreFromTrash_Field9_Field2 `protobuf:"bytes,2,opt,name=field2,proto3" json:"field2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreFromTrash_Field9) Reset() {
	*x = RestoreFromTrash_Field9{}
	mi := &file___proto_RestoreFromTrash_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreFromTrash_Field9) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreFromTrash_Field9) ProtoMessage() {}

func (x *RestoreFromTrash_Field9) ProtoReflect() protoreflect.Message {
	mi := &file___proto_RestoreFromTrash_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreFromTrash_Field9.ProtoReflect.Descriptor instead.
func (*RestoreFromTrash_Field9) Descriptor() ([]byte, []int) {
	return file___proto_RestoreFromTrash_proto_rawDescGZIP(), []int{0, 1}
}

func (x *RestoreFromTrash_Field9) GetField1() int64 {
	if x != nil {
		return x.Field1
	}
	return 0
}

func (x *RestoreFromTrash_Field9) GetField2() *RestoreFromTrash_Field9_Field2 {
	if x != nil {
		return x.Field2
	}
	return nil
}

type RestoreFromTrash_Field8_Field4 struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Field2        *RestoreFromTrash_Field8_Field4_Empty  `protobuf:"bytes,2,opt,name=field2,proto3" json:"field2,omitempty"`
	Field3        *RestoreFromTrash_Field8_Field4_Field3 `protobuf:"bytes,3,opt,name=field3,proto3" json:"field3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreFromTrash_Field8_Field4) Reset() {
	*x = RestoreFromTrash_Field8_Field4{}
	mi := &file___proto_RestoreFromTrash_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreFromTrash_Field8_Field4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreFromTrash_Field8_Field4) ProtoMessage() {}

func (x *RestoreFromTrash_Field8_Field4) ProtoReflect() protoreflect.Message {
	mi := &file___proto_RestoreFromTrash_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreFromTrash_Field8_Field4.ProtoReflect.Descriptor instead.
func (*RestoreFromTrash_Field8_Field4) Descriptor() ([]byte, []int) {
	return file___proto_RestoreFromTrash_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *RestoreFromTrash_Field8_Field4) GetField2() *RestoreFromTrash_Field8_Field4_Empty {
	if x != nil {
		return x.Field2
	}
	return nil
}

func (x *RestoreFromTrash_Field8_Field4) GetField3() *RestoreFromTrash_Field8_Field4_Field3 {
	if x != nil {
		return x.Field3
	}
	return nil
}

type RestoreFromTrash_Field8_Field4_Field3 struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Field1        *RestoreFromTrash_Field8_Field4_Empty `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreFromTrash_Field8_Field4_Field3) Reset() {
	*x = RestoreFromTrash_Field8_Field4_Field3{}
	mi := &file___proto_RestoreFromTrash_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreFromTrash_Field8_Field4_Field3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreFromTrash_Field8_Field4_Field3) ProtoMessage() {}

func (x *RestoreFromTrash_Field8_Field4_Field3) ProtoReflect() protoreflect.Message {
	mi := &file___proto_RestoreFromTrash_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreFromTrash_Field8_Field4_Field3.ProtoReflect.Descriptor instead.
func (*RestoreFromTrash_Field8_Field4_Field3) Descriptor() ([]byte, []int) {
	return file___proto_RestoreFromTrash_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

func (x *RestoreFromTrash_Field8_Field4_Field3) GetField1() *RestoreFromTrash_Field8_Field4_Empty {
	if x != nil {
		return x.Field1
	}
	return nil
}

type RestoreFromTrash_Field8_Field4_Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreFromTrash_Field8_Field4_Empty) Reset() {
	*x = RestoreFromTrash_Field8_Field4_Empty{}
	mi := &file___proto_RestoreFromTrash_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreFromTrash_Field8_Field4_Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreFromTrash_Field8_Field4_Empty) ProtoMessage() {}

func (x *RestoreFromTrash_Field8_Field4_Empty) ProtoReflect() protoreflect.Message {
	mi := &file___proto_RestoreFromTrash_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreFromTrash_Field8_Field4_Empty.ProtoReflect.Descriptor instead.
func (*RestoreFromTrash_Field8_Field4_Empty) Descriptor() ([]byte, []int) {
	return file___proto_RestoreFromTrash_proto_rawDescGZIP(), []int{0, 0, 0, 1}
}

type RestoreFromTrash_Field9_Field2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field1        int64                  `protobuf:"varint,1,opt,name=field1,proto3" json:"field1,omitempty"` // client_version_code
	Field2        string                 `protobuf:"bytes,2,opt,name=field2,proto3" json:"field2,omitempty"`  // android_api_version as string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreFromTrash_Field9_Field2) Reset() {
	*x = RestoreFromTrash_Field9_Field2{}
	mi := &file___proto_RestoreFromTrash_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreFromTrash_Field9_Field2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreFromTrash_Field9_Field2) ProtoMessage() {}

func (x *RestoreFromTrash_Field9_Field2) ProtoReflect() protoreflect.Message {
	mi := &file___proto_RestoreFromTrash_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreFromTrash_Field9_Field2.ProtoReflect.Descriptor instead.
func (*RestoreFromTrash_Field9_Field2) Descriptor() ([]byte, []int) {
	return file___proto_RestoreFromTrash_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *RestoreFromTrash_Field9_Field2) GetField1() int64 {
	if x != nil {
		return x.Field1
	}
	return 0
}

func (x *RestoreFromTrash_Field9_Field2) GetField2() string {
	if x != nil {
		return x.Field2
	}
	return ""
}

var File___proto_RestoreFromTrash_proto protoreflect.FileDescriptor

const file___proto_RestoreFromTrash_proto_rawDesc = "" +
	"\n" +
	"\x1d.proto/RestoreFromTrash.proto\"\xf9\x04\n" +
	"\x10RestoreFromTrash\x12\x16\n" +
	"\x06field2\x18\x02 \x01(\x03R\x06field2\x12\x1b\n" +
	"\titem_keys\x18\x03 \x03(\tR\bitemKeys\x12\x16\n" +
	"\x06field4\x18\x04 \x01(\x03R\x06field4\x120\n" +
	"\x06field8\x18\b \x01(\v2\x18.RestoreFromTrash.Field8R\x06field8\x120\n" +
	"\x06field9\x18\t \x01(\v2\x18.RestoreFromTrash.Field9R\x06field9\x1a\x9d\x02\n" +
	"\x06Field8\x127\n" +
	"\x06field4\x18\x04 \x01(\v2\x1f.RestoreFromTrash.Field8.Field4R\x06field4\x1a\xd9\x01\n" +
	"\x06Field4\x12=\n" +
	"\x06field2\x18\x02 \x01(\v2%.RestoreFromTrash.Field8.Field4.EmptyR\x06field2\x12>\n" +
	"\x06field3\x18\x03 \x01(\v2&.RestoreFromTrash.Field8.Field4.Field3R\x06field3\x1aG\n" +
	"\x06Field3\x12=\n" +
	"\x06field1\x18\x01 \x01(\v2%.RestoreFromTrash.Field8.Field4.EmptyR\x06field1\x1a\a\n" +
	"\x05Empty\x1a\x93\x01\n" +
	"\x06Field9\x12\x16\n" +
	"\x06field1\x18\x01 \x01(\x03R\x06field1\x127\n" +
	"\x06field2\x18\x02 \x01(\v2\x1f.RestoreFromTrash.Field9.Field2R\x06field2\x1a8\n" +
	"\x06Field2\x12\x16\n" +
	"\x06field1\x18\x01 \x01(\x03R\x06field1\x12\x16\n" +
	"\x06field2\x18\x02 \x01(\tR\x06field2B\x05Z\x03/pbb\x06proto3"

var (
	file___proto_RestoreFromTrash_proto_rawDescOnce sync.Once
	file___proto_RestoreFromTrash_proto_rawDescData []byte
)

func file___proto_RestoreFromTrash_proto_rawDescGZIP() []byte {
	file___proto_RestoreFromTrash_proto_rawDescOnce.Do(func() {
		file___proto_RestoreFromTrash_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file___proto_RestoreFromTrash_proto_rawDesc), len(file___proto_RestoreFromTrash_proto_rawDesc)))
	})
	return file___proto_RestoreFromTrash_proto_rawDescData
}

var file___proto_RestoreFromTrash_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file___proto_RestoreFromTrash_proto_goTypes = []any{
	(*RestoreFromTrash)(nil),                      // 0: RestoreFromTrash
	(*RestoreFromTrash_Field8)(nil),               // 1: RestoreFromTrash.Field8
	(*RestoreFromTrash_Field9)(nil),               // 2: RestoreFromTrash.Field9
	(*RestoreFromTrash_Field8_Field4)(nil),        // 3: RestoreFromTrash.Field8.Field4
	(*RestoreFromTrash_Field8_Field4_Field3)(nil), // 4: RestoreFromTrash.Field8.Field4.Field3
	(*RestoreFromTrash_Field8_Field4_Empty)(nil),  // 5: RestoreFromTrash.Field8.Field4.Empty
	(*RestoreFromTrash_Field9_Field2)(nil),        // 6: RestoreFromTrash.Field9.Field2
}
var file___proto_RestoreFromTrash_proto_depIdxs = []int32{
	1, // 0: RestoreFromTrash.field8:type_name -> RestoreFromTrash.Field8
	2, // 1: RestoreFromTrash.field9:type_name -> RestoreFromTrash.Field9
	3, // 2: RestoreFromTrash.Field8.field4:type_name -> RestoreFromTrash.Field8.Field4
	6, // 3: RestoreFromTrash.Field9.field2:type_name -> RestoreFromTrash.Field9.Field2
	5, // 4: RestoreFromTrash.Field8.Field4.field2:type_name -> RestoreFromTrash.Field8.Field4.Empty
	4, // 5: RestoreFromTrash.Field8.Field4.field3:type_name -> RestoreFromTrash.Field8.Field4.Field3
	5, // 6: RestoreFromTrash.Field8.Field4.Field3.field1:type_name -> RestoreFromTrash.Field8.Field4.Empty
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file___proto_RestoreFromTrash_proto_init() }
func file___proto_RestoreFromTrash_proto_init() {
	if File___proto_RestoreFromTrash_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file___proto_RestoreFromTrash_proto_rawDesc), len(file___proto_RestoreFromTrash_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file___proto_RestoreFromTrash_proto_goTypes,
		DependencyIndexes: file___proto_RestoreFromTrash_proto_depIdxs,
		MessageInfos:      file___proto_RestoreFromTrash_proto_msgTypes,
	}.Build()
	File___proto_RestoreFromTrash_proto = out.File
	file___proto_RestoreFromTrash_proto_goTypes = nil
	file___proto_RestoreFromTrash_proto_depIdxs = nil
}
