// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: SetArchived.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SetArchived is used to archive or unarchive media items
type SetArchived struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Items         []*SetArchived_ArchivedItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Field3        int64                       `protobuf:"varint,3,opt,name=field3,proto3" json:"field3,omitempty"` // constant: 1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetArchived) Reset() {
	*x = SetArchived{}
	mi := &file_SetArchived_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetArchived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetArchived) ProtoMessage() {}

func (x *SetArchived) ProtoReflect() protoreflect.Message {
	mi := &file_SetArchived_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetArchived.ProtoReflect.Descriptor instead.
func (*SetArchived) Descriptor() ([]byte, []int) {
	return file_SetArchived_proto_rawDescGZIP(), []int{0}
}

func (x *SetArchived) GetItems() []*SetArchived_ArchivedItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SetArchived) GetField3() int64 {
	if x != nil {
		return x.Field3
	}
	return 0
}

type SetArchived_ArchivedItem struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	ItemKey       string                     `protobuf:"bytes,1,opt,name=item_key,json=itemKey,proto3" json:"item_key,omitempty"` // mediaKey or dedupKey (URL-safe base64 encoded SHA1 hash)
	Action        *SetArchived_ArchiveAction `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetArchived_ArchivedItem) Reset() {
	*x = SetArchived_ArchivedItem{}
	mi := &file_SetArchived_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetArchived_ArchivedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetArchived_ArchivedItem) ProtoMessage() {}

func (x *SetArchived_ArchivedItem) ProtoReflect() protoreflect.Message {
	mi := &file_SetArchived_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetArchived_ArchivedItem.ProtoReflect.Descriptor instead.
func (*SetArchived_ArchivedItem) Descriptor() ([]byte, []int) {
	return file_SetArchived_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SetArchived_ArchivedItem) GetItemKey() string {
	if x != nil {
		return x.ItemKey
	}
	return ""
}

func (x *SetArchived_ArchivedItem) GetAction() *SetArchived_ArchiveAction {
	if x != nil {
		return x.Action
	}
	return nil
}

type SetArchived_ArchiveAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        int64                  `protobuf:"varint,1,opt,name=action,proto3" json:"action,omitempty"` // 1 = archive, 2 = unarchive
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetArchived_ArchiveAction) Reset() {
	*x = SetArchived_ArchiveAction{}
	mi := &file_SetArchived_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetArchived_ArchiveAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetArchived_ArchiveAction) ProtoMessage() {}

func (x *SetArchived_ArchiveAction) ProtoReflect() protoreflect.Message {
	mi := &file_SetArchived_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetArchived_ArchiveAction.ProtoReflect.Descriptor instead.
func (*SetArchived_ArchiveAction) Descriptor() ([]byte, []int) {
	return file_SetArchived_proto_rawDescGZIP(), []int{0, 1}
}

func (x *SetArchived_ArchiveAction) GetAction() int64 {
	if x != nil {
		return x.Action
	}
	return 0
}

var File_SetArchived_proto protoreflect.FileDescriptor

const file_SetArchived_proto_rawDesc = "" +
	"\n" +
	"\x11SetArchived.proto\"\xde\x01\n" +
	"\vSetArchived\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.SetArchived.ArchivedItemR\x05items\x12\x16\n" +
	"\x06field3\x18\x03 \x01(\x03R\x06field3\x1a]\n" +
	"\fArchivedItem\x12\x19\n" +
	"\bitem_key\x18\x01 \x01(\tR\aitemKey\x122\n" +
	"\x06action\x18\x02 \x01(\v2\x1a.SetArchived.ArchiveActionR\x06action\x1a'\n" +
	"\rArchiveAction\x12\x16\n" +
	"\x06action\x18\x01 \x01(\x03R\x06actionB\x05Z\x03/pbb\x06proto3"

var (
	file_SetArchived_proto_rawDescOnce sync.Once
	file_SetArchived_proto_rawDescData []byte
)

func file_SetArchived_proto_rawDescGZIP() []byte {
	file_SetArchived_proto_rawDescOnce.Do(func() {
		file_SetArchived_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SetArchived_proto_rawDesc), len(file_SetArchived_proto_rawDesc)))
	})
	return file_SetArchived_proto_rawDescData
}

var file_SetArchived_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_SetArchived_proto_goTypes = []any{
	(*SetArchived)(nil),               // 0: SetArchived
	(*SetArchived_ArchivedItem)(nil),  // 1: SetArchived.ArchivedItem
	(*SetArchived_ArchiveAction)(nil), // 2: SetArchived.ArchiveAction
}
var file_SetArchived_proto_depIdxs = []int32{
	1, // 0: SetArchived.items:type_name -> SetArchived.ArchivedItem
	2, // 1: SetArchived.ArchivedItem.action:type_name -> SetArchived.ArchiveAction
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_SetArchived_proto_init() }
func file_SetArchived_proto_init() {
	if File_SetArchived_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SetArchived_proto_rawDesc), len(file_SetArchived_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SetArchived_proto_goTypes,
		DependencyIndexes: file_SetArchived_proto_depIdxs,
		MessageInfos:      file_SetArchived_proto_msgTypes,
	}.Build()
	File_SetArchived_proto = out.File
	file_SetArchived_proto_goTypes = nil
	file_SetArchived_proto_depIdxs = nil
}
