// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: SetCaption.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetCaption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Caption       string                 `protobuf:"bytes,2,opt,name=caption,proto3" json:"caption,omitempty"`
	ItemKey       string                 `protobuf:"bytes,3,opt,name=item_key,json=itemKey,proto3" json:"item_key,omitempty"` // mediaKey or dedupKey
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCaption) Reset() {
	*x = SetCaption{}
	mi := &file_SetCaption_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCaption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCaption) ProtoMessage() {}

func (x *SetCaption) ProtoReflect() protoreflect.Message {
	mi := &file_SetCaption_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCaption.ProtoReflect.Descriptor instead.
func (*SetCaption) Descriptor() ([]byte, []int) {
	return file_SetCaption_proto_rawDescGZIP(), []int{0}
}

func (x *SetCaption) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *SetCaption) GetItemKey() string {
	if x != nil {
		return x.ItemKey
	}
	return ""
}

var File_SetCaption_proto protoreflect.FileDescriptor

const file_SetCaption_proto_rawDesc = "" +
	"\n" +
	"\x10SetCaption.proto\"A\n" +
	"\n" +
	"SetCaption\x12\x18\n" +
	"\acaption\x18\x02 \x01(\tR\acaption\x12\x19\n" +
	"\bitem_key\x18\x03 \x01(\tR\aitemKeyB\x05Z\x03/pbb\x06proto3"

var (
	file_SetCaption_proto_rawDescOnce sync.Once
	file_SetCaption_proto_rawDescData []byte
)

func file_SetCaption_proto_rawDescGZIP() []byte {
	file_SetCaption_proto_rawDescOnce.Do(func() {
		file_SetCaption_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SetCaption_proto_rawDesc), len(file_SetCaption_proto_rawDesc)))
	})
	return file_SetCaption_proto_rawDescData
}

var file_SetCaption_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SetCaption_proto_goTypes = []any{
	(*SetCaption)(nil), // 0: SetCaption
}
var file_SetCaption_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_SetCaption_proto_init() }
func file_SetCaption_proto_init() {
	if File_SetCaption_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SetCaption_proto_rawDesc), len(file_SetCaption_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SetCaption_proto_goTypes,
		DependencyIndexes: file_SetCaption_proto_depIdxs,
		MessageInfos:      file_SetCaption_proto_msgTypes,
	}.Build()
	File_SetCaption_proto = out.File
	file_SetCaption_proto_goTypes = nil
	file_SetCaption_proto_depIdxs = nil
}
