// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: SetFavourite.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetFavourite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field1        *SetFavourite_Field1   `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	Field2        *SetFavourite_Field2   `protobuf:"bytes,2,opt,name=field2,proto3" json:"field2,omitempty"`
	Field3        *SetFavourite_Field3   `protobuf:"bytes,3,opt,name=field3,proto3" json:"field3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFavourite) Reset() {
	*x = SetFavourite{}
	mi := &file_SetFavourite_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFavourite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFavourite) ProtoMessage() {}

func (x *SetFavourite) ProtoReflect() protoreflect.Message {
	mi := &file_SetFavourite_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFavourite.ProtoReflect.Descriptor instead.
func (*SetFavourite) Descriptor() ([]byte, []int) {
	return file_SetFavourite_proto_rawDescGZIP(), []int{0}
}

func (x *SetFavourite) GetField1() *SetFavourite_Field1 {
	if x != nil {
		return x.Field1
	}
	return nil
}

func (x *SetFavourite) GetField2() *SetFavourite_Field2 {
	if x != nil {
		return x.Field2
	}
	return nil
}

func (x *SetFavourite) GetField3() *SetFavourite_Field3 {
	if x != nil {
		return x.Field3
	}
	return nil
}

type SetFavourite_Field1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemKey       string                 `protobuf:"bytes,2,opt,name=item_key,json=itemKey,proto3" json:"item_key,omitempty"` // mediaKey or dedupKey
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFavourite_Field1) Reset() {
	*x = SetFavourite_Field1{}
	mi := &file_SetFavourite_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFavourite_Field1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFavourite_Field1) ProtoMessage() {}

func (x *SetFavourite_Field1) ProtoReflect() protoreflect.Message {
	mi := &file_SetFavourite_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFavourite_Field1.ProtoReflect.Descriptor instead.
func (*SetFavourite_Field1) Descriptor() ([]byte, []int) {
	return file_SetFavourite_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SetFavourite_Field1) GetItemKey() string {
	if x != nil {
		return x.ItemKey
	}
	return ""
}

type SetFavourite_Field2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        int64                  `protobuf:"varint,1,opt,name=action,proto3" json:"action,omitempty"` // 1 = favourite, 2 = unfavourite
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFavourite_Field2) Reset() {
	*x = SetFavourite_Field2{}
	mi := &file_SetFavourite_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFavourite_Field2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFavourite_Field2) ProtoMessage() {}

func (x *SetFavourite_Field2) ProtoReflect() protoreflect.Message {
	mi := &file_SetFavourite_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFavourite_Field2.ProtoReflect.Descriptor instead.
func (*SetFavourite_Field2) Descriptor() ([]byte, []int) {
	return file_SetFavourite_proto_rawDescGZIP(), []int{0, 1}
}

func (x *SetFavourite_Field2) GetAction() int64 {
	if x != nil {
		return x.Action
	}
	return 0
}

type SetFavourite_Field3 struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Field1        *SetFavourite_Field3_Field1Inner `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFavourite_Field3) Reset() {
	*x = SetFavourite_Field3{}
	mi := &file_SetFavourite_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFavourite_Field3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFavourite_Field3) ProtoMessage() {}

func (x *SetFavourite_Field3) ProtoReflect() protoreflect.Message {
	mi := &file_SetFavourite_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFavourite_Field3.ProtoReflect.Descriptor instead.
func (*SetFavourite_Field3) Descriptor() ([]byte, []int) {
	return file_SetFavourite_proto_rawDescGZIP(), []int{0, 2}
}

func (x *SetFavourite_Field3) GetField1() *SetFavourite_Field3_Field1Inner {
	if x != nil {
		return x.Field1
	}
	return nil
}

type SetFavourite_Field3_Field1Inner struct {
	state         protoimpl.MessageState                   `protogen:"open.v1"`
	Field19       *SetFavourite_Field3_Field1Inner_Field19 `protobuf:"bytes,19,opt,name=field19,proto3" json:"field19,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFavourite_Field3_Field1Inner) Reset() {
	*x = SetFavourite_Field3_Field1Inner{}
	mi := &file_SetFavourite_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFavourite_Field3_Field1Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFavourite_Field3_Field1Inner) ProtoMessage() {}

func (x *SetFavourite_Field3_Field1Inner) ProtoReflect() protoreflect.Message {
	mi := &file_SetFavourite_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFavourite_Field3_Field1Inner.ProtoReflect.Descriptor instead.
func (*SetFavourite_Field3_Field1Inner) Descriptor() ([]byte, []int) {
	return file_SetFavourite_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (x *SetFavourite_Field3_Field1Inner) GetField19() *SetFavourite_Field3_Field1Inner_Field19 {
	if x != nil {
		return x.Field19
	}
	return nil
}

type SetFavourite_Field3_Field1Inner_Field19 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFavourite_Field3_Field1Inner_Field19) Reset() {
	*x = SetFavourite_Field3_Field1Inner_Field19{}
	mi := &file_SetFavourite_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFavourite_Field3_Field1Inner_Field19) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFavourite_Field3_Field1Inner_Field19) ProtoMessage() {}

func (x *SetFavourite_Field3_Field1Inner_Field19) ProtoReflect() protoreflect.Message {
	mi := &file_SetFavourite_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFavourite_Field3_Field1Inner_Field19.ProtoReflect.Descriptor instead.
func (*SetFavourite_Field3_Field1Inner_Field19) Descriptor() ([]byte, []int) {
	return file_SetFavourite_proto_rawDescGZIP(), []int{0, 2, 0, 0}
}

var File_SetFavourite_proto protoreflect.FileDescriptor

const file_SetFavourite_proto_rawDesc = "" +
	"\n" +
	"\x12SetFavourite.proto\"\x82\x03\n" +
	"\fSetFavourite\x12,\n" +
	"\x06field1\x18\x01 \x01(\v2\x14.SetFavourite.Field1R\x06field1\x12,\n" +
	"\x06field2\x18\x02 \x01(\v2\x14.SetFavourite.Field2R\x06field2\x12,\n" +
	"\x06field3\x18\x03 \x01(\v2\x14.SetFavourite.Field3R\x06field3\x1a#\n" +
	"\x06Field1\x12\x19\n" +
	"\bitem_key\x18\x02 \x01(\tR\aitemKey\x1a \n" +
	"\x06Field2\x12\x16\n" +
	"\x06action\x18\x01 \x01(\x03R\x06action\x1a\xa0\x01\n" +
	"\x06Field3\x128\n" +
	"\x06field1\x18\x01 \x01(\v2 .SetFavourite.Field3.Field1InnerR\x06field1\x1a\\\n" +
	"\vField1Inner\x12B\n" +
	"\afield19\x18\x13 \x01(\v2(.SetFavourite.Field3.Field1Inner.Field19R\afield19\x1a\t\n" +
	"\aField19B\x05Z\x03/pbb\x06proto3"

var (
	file_SetFavourite_proto_rawDescOnce sync.Once
	file_SetFavourite_proto_rawDescData []byte
)

func file_SetFavourite_proto_rawDescGZIP() []byte {
	file_SetFavourite_proto_rawDescOnce.Do(func() {
		file_SetFavourite_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SetFavourite_proto_rawDesc), len(file_SetFavourite_proto_rawDesc)))
	})
	return file_SetFavourite_proto_rawDescData
}

var file_SetFavourite_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_SetFavourite_proto_goTypes = []any{
	(*SetFavourite)(nil),                            // 0: SetFavourite
	(*SetFavourite_Field1)(nil),                     // 1: SetFavourite.Field1
	(*SetFavourite_Field2)(nil),                     // 2: SetFavourite.Field2
	(*SetFavourite_Field3)(nil),                     // 3: SetFavourite.Field3
	(*SetFavourite_Field3_Field1Inner)(nil),         // 4: SetFavourite.Field3.Field1Inner
	(*SetFavourite_Field3_Field1Inner_Field19)(nil), // 5: SetFavourite.Field3.Field1Inner.Field19
}
var file_SetFavourite_proto_depIdxs = []int32{
	1, // 0: SetFavourite.field1:type_name -> SetFavourite.Field1
	2, // 1: SetFavourite.field2:type_name -> SetFavourite.Field2
	3, // 2: SetFavourite.field3:type_name -> SetFavourite.Field3
	4, // 3: SetFavourite.Field3.field1:type_name -> SetFavourite.Field3.Field1Inner
	5, // 4: SetFavourite.Field3.Field1Inner.field19:type_name -> SetFavourite.Field3.Field1Inner.Field19
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_SetFavourite_proto_init() }
func file_SetFavourite_proto_init() {
	if File_SetFavourite_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SetFavourite_proto_rawDesc), len(file_SetFavourite_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SetFavourite_proto_goTypes,
		DependencyIndexes: file_SetFavourite_proto_depIdxs,
		MessageInfos:      file_SetFavourite_proto_msgTypes,
	}.Build()
	File_SetFavourite_proto = out.File
	file_SetFavourite_proto_goTypes = nil
	file_SetFavourite_proto_depIdxs = nil
}
