// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: .proto/GetDownloadUrl.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDownloadUrl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field1        *GetDownloadUrl_Field1 `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	Field2        *GetDownloadUrl_Field2 `protobuf:"bytes,2,opt,name=field2,proto3" json:"field2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrl) Reset() {
	*x = GetDownloadUrl{}
	mi := &file___proto_GetDownloadUrl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrl) ProtoMessage() {}

func (x *GetDownloadUrl) ProtoReflect() protoreflect.Message {
	mi := &file___proto_GetDownloadUrl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrl.ProtoReflect.Descriptor instead.
func (*GetDownloadUrl) Descriptor() ([]byte, []int) {
	return file___proto_GetDownloadUrl_proto_rawDescGZIP(), []int{0}
}

func (x *GetDownloadUrl) GetField1() *GetDownloadUrl_Field1 {
	if x != nil {
		return x.Field1
	}
	return nil
}

func (x *GetDownloadUrl) GetField2() *GetDownloadUrl_Field2 {
	if x != nil {
		return x.Field2
	}
	return nil
}

type GetDownloadUrlResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Field1        *GetDownloadUrlResponse_Field1 `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrlResponse) Reset() {
	*x = GetDownloadUrlResponse{}
	mi := &file___proto_GetDownloadUrl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrlResponse) ProtoMessage() {}

func (x *GetDownloadUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file___proto_GetDownloadUrl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrlResponse.ProtoReflect.Descriptor instead.
func (*GetDownloadUrlResponse) Descriptor() ([]byte, []int) {
	return file___proto_GetDownloadUrl_proto_rawDescGZIP(), []int{1}
}

func (x *GetDownloadUrlResponse) GetField1() *GetDownloadUrlResponse_Field1 {
	if x != nil {
		return x.Field1
	}
	return nil
}

type GetDownloadUrl_Field1 struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Field1        *GetDownloadUrl_Field1_Field1Inner `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrl_Field1) Reset() {
	*x = GetDownloadUrl_Field1{}
	mi := &file___proto_GetDownloadUrl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrl_Field1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrl_Field1) ProtoMessage() {}

func (x *GetDownloadUrl_Field1) ProtoReflect() protoreflect.Message {
	mi := &file___proto_GetDownloadUrl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrl_Field1.ProtoReflect.Descriptor instead.
func (*GetDownloadUrl_Field1) Descriptor() ([]byte, []int) {
	return file___proto_GetDownloadUrl_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetDownloadUrl_Field1) GetField1() *GetDownloadUrl_Field1_Field1Inner {
	if x != nil {
		return x.Field1
	}
	return nil
}

type GetDownloadUrl_Field2 struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Field1        *GetDownloadUrl_Field2_Field1Type `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	Field5        *GetDownloadUrl_Field2_Field5Type `protobuf:"bytes,5,opt,name=field5,proto3" json:"field5,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrl_Field2) Reset() {
	*x = GetDownloadUrl_Field2{}
	mi := &file___proto_GetDownloadUrl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrl_Field2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrl_Field2) ProtoMessage() {}

func (x *GetDownloadUrl_Field2) ProtoReflect() protoreflect.Message {
	mi := &file___proto_GetDownloadUrl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrl_Field2.ProtoReflect.Descriptor instead.
func (*GetDownloadUrl_Field2) Descriptor() ([]byte, []int) {
	return file___proto_GetDownloadUrl_proto_rawDescGZIP(), []int{0, 1}
}

func (x *GetDownloadUrl_Field2) GetField1() *GetDownloadUrl_Field2_Field1Type {
	if x != nil {
		return x.Field1
	}
	return nil
}

func (x *GetDownloadUrl_Field2) GetField5() *GetDownloadUrl_Field2_Field5Type {
	if x != nil {
		return x.Field5
	}
	return nil
}

type GetDownloadUrl_Field1_Field1Inner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaKey      string                 `protobuf:"bytes,1,opt,name=media_key,json=mediaKey,proto3" json:"media_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrl_Field1_Field1Inner) Reset() {
	*x = GetDownloadUrl_Field1_Field1Inner{}
	mi := &file___proto_GetDownloadUrl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrl_Field1_Field1Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrl_Field1_Field1Inner) ProtoMessage() {}

func (x *GetDownloadUrl_Field1_Field1Inner) ProtoReflect() protoreflect.Message {
	mi := &file___proto_GetDownloadUrl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrl_Field1_Field1Inner.ProtoReflect.Descriptor instead.
func (*GetDownloadUrl_Field1_Field1Inner) Descriptor() ([]byte, []int) {
	return file___proto_GetDownloadUrl_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *GetDownloadUrl_Field1_Field1Inner) GetMediaKey() string {
	if x != nil {
		return x.MediaKey
	}
	return ""
}

type GetDownloadUrl_Field2_Field1Type struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	Field7        *GetDownloadUrl_Field2_Field1Type_Field7Type `protobuf:"bytes,7,opt,name=field7,proto3" json:"field7,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrl_Field2_Field1Type) Reset() {
	*x = GetDownloadUrl_Field2_Field1Type{}
	mi := &file___proto_GetDownloadUrl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrl_Field2_Field1Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrl_Field2_Field1Type) ProtoMessage() {}

func (x *GetDownloadUrl_Field2_Field1Type) ProtoReflect() protoreflect.Message {
	mi := &file___proto_GetDownloadUrl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrl_Field2_Field1Type.ProtoReflect.Descriptor instead.
func (*GetDownloadUrl_Field2_Field1Type) Descriptor() ([]byte, []int) {
	return file___proto_GetDownloadUrl_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *GetDownloadUrl_Field2_Field1Type) GetField7() *GetDownloadUrl_Field2_Field1Type_Field7Type {
	if x != nil {
		return x.Field7
	}
	return nil
}

type GetDownloadUrl_Field2_Field5Type struct {
	state         protoimpl.MessageState                        `protogen:"open.v1"`
	Field2        *GetDownloadUrl_Field2_Field5Type_Field2Type  `protobuf:"bytes,2,opt,name=field2,proto3" json:"field2,omitempty"`
	Field3        *GetDownloadUrl_Field2_Field5Type_Field3Type  `protobuf:"bytes,3,opt,name=field3,proto3" json:"field3,omitempty"`
	Field5        *GetDownloadUrl_Field2_Field5Type_Field5Inner `protobuf:"bytes,5,opt,name=field5,proto3" json:"field5,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrl_Field2_Field5Type) Reset() {
	*x = GetDownloadUrl_Field2_Field5Type{}
	mi := &file___proto_GetDownloadUrl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrl_Field2_Field5Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrl_Field2_Field5Type) ProtoMessage() {}

func (x *GetDownloadUrl_Field2_Field5Type) ProtoReflect() protoreflect.Message {
	mi := &file___proto_GetDownloadUrl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrl_Field2_Field5Type.ProtoReflect.Descriptor instead.
func (*GetDownloadUrl_Field2_Field5Type) Descriptor() ([]byte, []int) {
	return file___proto_GetDownloadUrl_proto_rawDescGZIP(), []int{0, 1, 1}
}

func (x *GetDownloadUrl_Field2_Field5Type) GetField2() *GetDownloadUrl_Field2_Field5Type_Field2Type {
	if x != nil {
		return x.Field2
	}
	return nil
}

func (x *GetDownloadUrl_Field2_Field5Type) GetField3() *GetDownloadUrl_Field2_Field5Type_Field3Type {
	if x != nil {
		return x.Field3
	}
	return nil
}

func (x *GetDownloadUrl_Field2_Field5Type) GetField5() *GetDownloadUrl_Field2_Field5Type_Field5Inner {
	if x != nil {
		return x.Field5
	}
	return nil
}

type GetDownloadUrl_Field2_Field1Type_Field7Type struct {
	state         protoimpl.MessageState                                  `protogen:"open.v1"`
	Field2        *GetDownloadUrl_Field2_Field1Type_Field7Type_Field2Type `protobuf:"bytes,2,opt,name=field2,proto3" json:"field2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrl_Field2_Field1Type_Field7Type) Reset() {
	*x = GetDownloadUrl_Field2_Field1Type_Field7Type{}
	mi := &file___proto_GetDownloadUrl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrl_Field2_Field1Type_Field7Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrl_Field2_Field1Type_Field7Type) ProtoMessage() {}

func (x *GetDownloadUrl_Field2_Field1Type_Field7Type) ProtoReflect() protoreflect.Message {
	mi := &file___proto_GetDownloadUrl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrl_Field2_Field1Type_Field7Type.ProtoReflect.Descriptor instead.
func (*GetDownloadUrl_Field2_Field1Type_Field7Type) Descriptor() ([]byte, []int) {
	return file___proto_GetDownloadUrl_proto_rawDescGZIP(), []int{0, 1, 0, 0}
}

func (x *GetDownloadUrl_Field2_Field1Type_Field7Type) GetField2() *GetDownloadUrl_Field2_Field1Type_Field7Type_Field2Type {
	if x != nil {
		return x.Field2
	}
	return nil
}

type GetDownloadUrl_Field2_Field1Type_Field7Type_Field2Type struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrl_Field2_Field1Type_Field7Type_Field2Type) Reset() {
	*x = GetDownloadUrl_Field2_Field1Type_Field7Type_Field2Type{}
	mi := &file___proto_GetDownloadUrl_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrl_Field2_Field1Type_Field7Type_Field2Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrl_Field2_Field1Type_Field7Type_Field2Type) ProtoMessage() {}

func (x *GetDownloadUrl_Field2_Field1Type_Field7Type_Field2Type) ProtoReflect() protoreflect.Message {
	mi := &file___proto_GetDownloadUrl_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrl_Field2_Field1Type_Field7Type_Field2Type.ProtoReflect.Descriptor instead.
func (*GetDownloadUrl_Field2_Field1Type_Field7Type_Field2Type) Descriptor() ([]byte, []int) {
	return file___proto_GetDownloadUrl_proto_rawDescGZIP(), []int{0, 1, 0, 0, 0}
}

type GetDownloadUrl_Field2_Field5Type_Field2Type struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrl_Field2_Field5Type_Field2Type) Reset() {
	*x = GetDownloadUrl_Field2_Field5Type_Field2Type{}
	mi := &file___proto_GetDownloadUrl_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrl_Field2_Field5Type_Field2Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrl_Field2_Field5Type_Field2Type) ProtoMessage() {}

func (x *GetDownloadUrl_Field2_Field5Type_Field2Type) ProtoReflect() protoreflect.Message {
	mi := &file___proto_GetDownloadUrl_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrl_Field2_Field5Type_Field2Type.ProtoReflect.Descriptor instead.
func (*GetDownloadUrl_Field2_Field5Type_Field2Type) Descriptor() ([]byte, []int) {
	return file___proto_GetDownloadUrl_proto_rawDescGZIP(), []int{0, 1, 1, 0}
}

type GetDownloadUrl_Field2_Field5Type_Field3Type struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrl_Field2_Field5Type_Field3Type) Reset() {
	*x = GetDownloadUrl_Field2_Field5Type_Field3Type{}
	mi := &file___proto_GetDownloadUrl_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrl_Field2_Field5Type_Field3Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrl_Field2_Field5Type_Field3Type) ProtoMessage() {}

func (x *GetDownloadUrl_Field2_Field5Type_Field3Type) ProtoReflect() protoreflect.Message {
	mi := &file___proto_GetDownloadUrl_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrl_Field2_Field5Type_Field3Type.ProtoReflect.Descriptor instead.
func (*GetDownloadUrl_Field2_Field5Type_Field3Type) Descriptor() ([]byte, []int) {
	return file___proto_GetDownloadUrl_proto_rawDescGZIP(), []int{0, 1, 1, 1}
}

type GetDownloadUrl_Field2_Field5Type_Field5Inner struct {
	state         protoimpl.MessageState                                   `protogen:"open.v1"`
	Field1        *GetDownloadUrl_Field2_Field5Type_Field5Inner_Field1Type `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	Field3        int64                                                    `protobuf:"varint,3,opt,name=field3,proto3" json:"field3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrl_Field2_Field5Type_Field5Inner) Reset() {
	*x = GetDownloadUrl_Field2_Field5Type_Field5Inner{}
	mi := &file___proto_GetDownloadUrl_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrl_Field2_Field5Type_Field5Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrl_Field2_Field5Type_Field5Inner) ProtoMessage() {}

func (x *GetDownloadUrl_Field2_Field5Type_Field5Inner) ProtoReflect() protoreflect.Message {
	mi := &file___proto_GetDownloadUrl_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrl_Field2_Field5Type_Field5Inner.ProtoReflect.Descriptor instead.
func (*GetDownloadUrl_Field2_Field5Type_Field5Inner) Descriptor() ([]byte, []int) {
	return file___proto_GetDownloadUrl_proto_rawDescGZIP(), []int{0, 1, 1, 2}
}

func (x *GetDownloadUrl_Field2_Field5Type_Field5Inner) GetField1() *GetDownloadUrl_Field2_Field5Type_Field5Inner_Field1Type {
	if x != nil {
		return x.Field1
	}
	return nil
}

func (x *GetDownloadUrl_Field2_Field5Type_Field5Inner) GetField3() int64 {
	if x != nil {
		return x.Field3
	}
	return 0
}

type GetDownloadUrl_Field2_Field5Type_Field5Inner_Field1Type struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrl_Field2_Field5Type_Field5Inner_Field1Type) Reset() {
	*x = GetDownloadUrl_Field2_Field5Type_Field5Inner_Field1Type{}
	mi := &file___proto_GetDownloadUrl_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrl_Field2_Field5Type_Field5Inner_Field1Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrl_Field2_Field5Type_Field5Inner_Field1Type) ProtoMessage() {}

func (x *GetDownloadUrl_Field2_Field5Type_Field5Inner_Field1Type) ProtoReflect() protoreflect.Message {
	mi := &file___proto_GetDownloadUrl_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrl_Field2_Field5Type_Field5Inner_Field1Type.ProtoReflect.Descriptor instead.
func (*GetDownloadUrl_Field2_Field5Type_Field5Inner_Field1Type) Descriptor() ([]byte, []int) {
	return file___proto_GetDownloadUrl_proto_rawDescGZIP(), []int{0, 1, 1, 2, 0}
}

type GetDownloadUrlResponse_Field1 struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Field5        *GetDownloadUrlResponse_Field1_Field5 `protobuf:"bytes,5,opt,name=field5,proto3" json:"field5,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrlResponse_Field1) Reset() {
	*x = GetDownloadUrlResponse_Field1{}
	mi := &file___proto_GetDownloadUrl_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrlResponse_Field1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrlResponse_Field1) ProtoMessage() {}

func (x *GetDownloadUrlResponse_Field1) ProtoReflect() protoreflect.Message {
	mi := &file___proto_GetDownloadUrl_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrlResponse_Field1.ProtoReflect.Descriptor instead.
func (*GetDownloadUrlResponse_Field1) Descriptor() ([]byte, []int) {
	return file___proto_GetDownloadUrl_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetDownloadUrlResponse_Field1) GetField5() *GetDownloadUrlResponse_Field1_Field5 {
	if x != nil {
		return x.Field5
	}
	return nil
}

type GetDownloadUrlResponse_Field1_Field5 struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	Field1        int64                                        `protobuf:"varint,1,opt,name=field1,proto3" json:"field1,omitempty"`
	Field3        *GetDownloadUrlResponse_Field1_Field5_Field3 `protobuf:"bytes,3,opt,name=field3,proto3" json:"field3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrlResponse_Field1_Field5) Reset() {
	*x = GetDownloadUrlResponse_Field1_Field5{}
	mi := &file___proto_GetDownloadUrl_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrlResponse_Field1_Field5) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrlResponse_Field1_Field5) ProtoMessage() {}

func (x *GetDownloadUrlResponse_Field1_Field5) ProtoReflect() protoreflect.Message {
	mi := &file___proto_GetDownloadUrl_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrlResponse_Field1_Field5.ProtoReflect.Descriptor instead.
func (*GetDownloadUrlResponse_Field1_Field5) Descriptor() ([]byte, []int) {
	return file___proto_GetDownloadUrl_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *GetDownloadUrlResponse_Field1_Field5) GetField1() int64 {
	if x != nil {
		return x.Field1
	}
	return 0
}

func (x *GetDownloadUrlResponse_Field1_Field5) GetField3() *GetDownloadUrlResponse_Field1_Field5_Field3 {
	if x != nil {
		return x.Field3
	}
	return nil
}

type GetDownloadUrlResponse_Field1_Field5_Field3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field1        string                 `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	Field3        int64                  `protobuf:"varint,3,opt,name=field3,proto3" json:"field3,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,5,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrlResponse_Field1_Field5_Field3) Reset() {
	*x = GetDownloadUrlResponse_Field1_Field5_Field3{}
	mi := &file___proto_GetDownloadUrl_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrlResponse_Field1_Field5_Field3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrlResponse_Field1_Field5_Field3) ProtoMessage() {}

func (x *GetDownloadUrlResponse_Field1_Field5_Field3) ProtoReflect() protoreflect.Message {
	mi := &file___proto_GetDownloadUrl_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrlResponse_Field1_Field5_Field3.ProtoReflect.Descriptor instead.
func (*GetDownloadUrlResponse_Field1_Field5_Field3) Descriptor() ([]byte, []int) {
	return file___proto_GetDownloadUrl_proto_rawDescGZIP(), []int{1, 0, 0, 0}
}

func (x *GetDownloadUrlResponse_Field1_Field5_Field3) GetField1() string {
	if x != nil {
		return x.Field1
	}
	return ""
}

func (x *GetDownloadUrlResponse_Field1_Field5_Field3) GetField3() int64 {
	if x != nil {
		return x.Field3
	}
	return 0
}

func (x *GetDownloadUrlResponse_Field1_Field5_Field3) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

var File___proto_GetDownloadUrl_proto protoreflect.FileDescriptor

const file___proto_GetDownloadUrl_proto_rawDesc = "" +
	"\n" +
	"\x1b.proto/GetDownloadUrl.proto\"\xab\a\n" +
	"\x0eGetDownloadUrl\x12.\n" +
	"\x06field1\x18\x01 \x01(\v2\x16.GetDownloadUrl.Field1R\x06field1\x12.\n" +
	"\x06field2\x18\x02 \x01(\v2\x16.GetDownloadUrl.Field2R\x06field2\x1ap\n" +
	"\x06Field1\x12:\n" +
	"\x06field1\x18\x01 \x01(\v2\".GetDownloadUrl.Field1.Field1InnerR\x06field1\x1a*\n" +
	"\vField1Inner\x12\x1b\n" +
	"\tmedia_key\x18\x01 \x01(\tR\bmediaKey\x1a\xc6\x05\n" +
	"\x06Field2\x129\n" +
	"\x06field1\x18\x01 \x01(\v2!.GetDownloadUrl.Field2.Field1TypeR\x06field1\x129\n" +
	"\x06field5\x18\x05 \x01(\v2!.GetDownloadUrl.Field2.Field5TypeR\x06field5\x1a\xbf\x01\n" +
	"\n" +
	"Field1Type\x12D\n" +
	"\x06field7\x18\a \x01(\v2,.GetDownloadUrl.Field2.Field1Type.Field7TypeR\x06field7\x1ak\n" +
	"\n" +
	"Field7Type\x12O\n" +
	"\x06field2\x18\x02 \x01(\v27.GetDownloadUrl.Field2.Field1Type.Field7Type.Field2TypeR\x06field2\x1a\f\n" +
	"\n" +
	"Field2Type\x1a\x83\x03\n" +
	"\n" +
	"Field5Type\x12D\n" +
	"\x06field2\x18\x02 \x01(\v2,.GetDownloadUrl.Field2.Field5Type.Field2TypeR\x06field2\x12D\n" +
	"\x06field3\x18\x03 \x01(\v2,.GetDownloadUrl.Field2.Field5Type.Field3TypeR\x06field3\x12E\n" +
	"\x06field5\x18\x05 \x01(\v2-.GetDownloadUrl.Field2.Field5Type.Field5InnerR\x06field5\x1a\f\n" +
	"\n" +
	"Field2Type\x1a\f\n" +
	"\n" +
	"Field3Type\x1a\x85\x01\n" +
	"\vField5Inner\x12P\n" +
	"\x06field1\x18\x01 \x01(\v28.GetDownloadUrl.Field2.Field5Type.Field5Inner.Field1TypeR\x06field1\x12\x16\n" +
	"\x06field3\x18\x03 \x01(\x03R\x06field3\x1a\f\n" +
	"\n" +
	"Field1Type\"\xe0\x02\n" +
	"\x16GetDownloadUrlResponse\x126\n" +
	"\x06field1\x18\x01 \x01(\v2\x1e.GetDownloadUrlResponse.Field1R\x06field1\x1a\x8d\x02\n" +
	"\x06Field1\x12=\n" +
	"\x06field5\x18\x05 \x01(\v2%.GetDownloadUrlResponse.Field1.Field5R\x06field5\x1a\xc3\x01\n" +
	"\x06Field5\x12\x16\n" +
	"\x06field1\x18\x01 \x01(\x03R\x06field1\x12D\n" +
	"\x06field3\x18\x03 \x01(\v2,.GetDownloadUrlResponse.Field1.Field5.Field3R\x06field3\x1a[\n" +
	"\x06Field3\x12\x16\n" +
	"\x06field1\x18\x01 \x01(\tR\x06field1\x12\x16\n" +
	"\x06field3\x18\x03 \x01(\x03R\x06field3\x12!\n" +
	"\fdownload_url\x18\x05 \x01(\tR\vdownloadUrlB\x05Z\x03/pbb\x06proto3"

var (
	file___proto_GetDownloadUrl_proto_rawDescOnce sync.Once
	file___proto_GetDownloadUrl_proto_rawDescData []byte
)

func file___proto_GetDownloadUrl_proto_rawDescGZIP() []byte {
	file___proto_GetDownloadUrl_proto_rawDescOnce.Do(func() {
		file___proto_GetDownloadUrl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file___proto_GetDownloadUrl_proto_rawDesc), len(file___proto_GetDownloadUrl_proto_rawDesc)))
	})
	return file___proto_GetDownloadUrl_proto_rawDescData
}

var file___proto_GetDownloadUrl_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file___proto_GetDownloadUrl_proto_goTypes = []any{
	(*GetDownloadUrl)(nil),                                          // 0: GetDownloadUrl
	(*GetDownloadUrlResponse)(nil),                                  // 1: GetDownloadUrlResponse
	(*GetDownloadUrl_Field1)(nil),                                   // 2: GetDownloadUrl.Field1
	(*GetDownloadUrl_Field2)(nil),                                   // 3: GetDownloadUrl.Field2
	(*GetDownloadUrl_Field1_Field1Inner)(nil),                       // 4: GetDownloadUrl.Field1.Field1Inner
	(*GetDownloadUrl_Field2_Field1Type)(nil),                        // 5: GetDownloadUrl.Field2.Field1Type
	(*GetDownloadUrl_Field2_Field5Type)(nil),                        // 6: GetDownloadUrl.Field2.Field5Type
	(*GetDownloadUrl_Field2_Field1Type_Field7Type)(nil),             // 7: GetDownloadUrl.Field2.Field1Type.Field7Type
	(*GetDownloadUrl_Field2_Field1Type_Field7Type_Field2Type)(nil),  // 8: GetDownloadUrl.Field2.Field1Type.Field7Type.Field2Type
	(*GetDownloadUrl_Field2_Field5Type_Field2Type)(nil),             // 9: GetDownloadUrl.Field2.Field5Type.Field2Type
	(*GetDownloadUrl_Field2_Field5Type_Field3Type)(nil),             // 10: GetDownloadUrl.Field2.Field5Type.Field3Type
	(*GetDownloadUrl_Field2_Field5Type_Field5Inner)(nil),            // 11: GetDownloadUrl.Field2.Field5Type.Field5Inner
	(*GetDownloadUrl_Field2_Field5Type_Field5Inner_Field1Type)(nil), // 12: GetDownloadUrl.Field2.Field5Type.Field5Inner.Field1Type
	(*GetDownloadUrlResponse_Field1)(nil),                           // 13: GetDownloadUrlResponse.Field1
	(*GetDownloadUrlResponse_Field1_Field5)(nil),                    // 14: GetDownloadUrlResponse.Field1.Field5
	(*GetDownloadUrlResponse_Field1_Field5_Field3)(nil),             // 15: GetDownloadUrlResponse.Field1.Field5.Field3
}
var file___proto_GetDownloadUrl_proto_depIdxs = []int32{
	2,  // 0: GetDownloadUrl.field1:type_name -> GetDownloadUrl.Field1
	3,  // 1: GetDownloadUrl.field2:type_name -> GetDownloadUrl.Field2
	13, // 2: GetDownloadUrlResponse.field1:type_name -> GetDownloadUrlResponse.Field1
	4,  // 3: GetDownloadUrl.Field1.field1:type_name -> GetDownloadUrl.Field1.Field1Inner
	5,  // 4: GetDownloadUrl.Field2.field1:type_name -> GetDownloadUrl.Field2.Field1Type
	6,  // 5: GetDownloadUrl.Field2.field5:type_name -> GetDownloadUrl.Field2.Field5Type
	7,  // 6: GetDownloadUrl.Field2.Field1Type.field7:type_name -> GetDownloadUrl.Field2.Field1Type.Field7Type
	9,  // 7: GetDownloadUrl.Field2.Field5Type.field2:type_name -> GetDownloadUrl.Field2.Field5Type.Field2Type
	10, // 8: GetDownloadUrl.Field2.Field5Type.field3:type_name -> GetDownloadUrl.Field2.Field5Type.Field3Type
	11, // 9: GetDownloadUrl.Field2.Field5Type.field5:type_name -> GetDownloadUrl.Field2.Field5Type.Field5Inner
	8,  // 10: GetDownloadUrl.Field2.Field1Type.Field7Type.field2:type_name -> GetDownloadUrl.Field2.Field1Type.Field7Type.Field2Type
	12, // 11: GetDownloadUrl.Field2.Field5Type.Field5Inner.field1:type_name -> GetDownloadUrl.Field2.Field5Type.Field5Inner.Field1Type
	14, // 12: GetDownloadUrlResponse.Field1.field5:type_name -> GetDownloadUrlResponse.Field1.Field5
	15, // 13: GetDownloadUrlResponse.Field1.Field5.field3:type_name -> GetDownloadUrlResponse.Field1.Field5.Field3
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file___proto_GetDownloadUrl_proto_init() }
func file___proto_GetDownloadUrl_proto_init() {
	if File___proto_GetDownloadUrl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file___proto_GetDownloadUrl_proto_rawDesc), len(file___proto_GetDownloadUrl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file___proto_GetDownloadUrl_proto_goTypes,
		DependencyIndexes: file___proto_GetDownloadUrl_proto_depIdxs,
		MessageInfos:      file___proto_GetDownloadUrl_proto_msgTypes,
	}.Build()
	File___proto_GetDownloadUrl_proto = out.File
	file___proto_GetDownloadUrl_proto_goTypes = nil
	file___proto_GetDownloadUrl_proto_depIdxs = nil
}
